export const lannguageDictAR ={
    "GOT_IT": "فهمتها",
    "about.copy_right": "Copyright © {{year}} Zoom Video Communications, Inc. All rights reserved.",
    "account_owner": "صاحب حساب",
    "allow_to_access": "Allow Zoom to access your camera and microphone",
    "app_signal.approved_by": "موافق عليه من قبل {{0}}",
    "app_signal.people": "الناس",
    "app_signal.tip_text_2": "انظر التطبيقات التي تصل إلى محتوى الاجتماع الخاص بك",
    "app_signal.unable_load2": "يتعذر تحميل التطبيقات مع إمكانية الوصول في الوقت الفعلي إلى معلوماتك.",
    "archiving.chat_1": "الدردشة (العامة والمباشرة)",
    "archiving.chat_2": "محادثة (عامة فقط)",
    "archiving.chat_disable_content": "لا يمكن أرشفة الرسائل المرسلة في الدردشة لأغراض الامتثال.",
    "archiving.chat_disable_title": "تم تعطيل الدردشة",
    "archiving.content1_sdk": "One or more participants in this meeting are subject to archiving based on their account's policy. Their {{content}} will receive content from this meeting and can share it with apps and others.",
    "archiving.content2_sdk": "By staying in this meeting, you consent to this meeting's {{content}} being archived.",
    "archiving.default_title": "يتم أرشفة هذا الاجتماع",
    "archiving.fail_content_sdk": "This meeting's {{features}} must be archived for compliance purposes.",
    "archiving.fail_title": "فشل الأرشفة",
    "archiving.subjects_combo_2_sdk": "{{0}} and {{1}}",
    "archiving.subjects_combo_3_sdk": "{{0}}, {{1}}, and {{2}}",
    "archiving.subjects_combo_4_sdk": "{{0}}, {{1}}, {{2}}, and {{3}}",
    "archiving.tips_1_sdk": "This meeting's {{subjects}} is being archived by the host's organization based on their account's policy. Their {{receiver}} will receive content from this meeting and can share it with apps and others.",
    "archiving.tips_2_sdk": "This meeting's {{subjects}} are being archived by the host's organization based on their account's policy. Their {{receiver}} will receive content from this meeting and can share it with apps and others.",
    "archiving.transcription": "النسخ",
    "ast.leave_tip": "توقف المساعد عن التحكم في الاجتماع",
    "ast.tip": "يتم التحكم في هذا الاجتماع من قبل مساعد",
    "background": "خلفية",
    "chat_disabled": "Chat disabled",
    "chat_message_header": "<0>{{senderName}}</0> <1>to</1> <2>{{receiverName}}</2>",
    "chat_new_message": "{{counts}} New Message",
    "chat_receiver_co_host": "( Co-host )",
    "chat_receiver_host": "( Host )",
    "chat_receiver_panelist": "( Panelist )",
    "chat_receiver_to": "To:",
    "choose_background": "اختر خلفية",
    "click_address_bar": "Click the lock icon to the left of your address bar. A pop-up will appear with a list of options.",
    "click_microphone_camera_option": "Click the drop-down list to the right of the Camera and Microphone option.",
    "common.cancel": "إلغاء",
    "common.connecting": "توصيل",
    "common.side_by_side_gallery": "جنبًا إلى جنب: المعرض",
    "common.side_by_side_speaker": "جنبًا إلى جنب: مكبر الصوت",
    "common.view": "منظر",
    "delete": "يمسح",
    "dialog.btn_cancel": "إلغاء",
    "dialog.btn_create": "إنشاء",
    "dialog.btn_endconf_webinar": "إنهاء الندوة عبر الويب",
    "dialog.btn_leaveconf_meeting": "مغادرة الاجتماع",
    "dialog.btn_retry": "أعد المحاولة",
    "dialog.gift_content6": "شكرا لاختيارك Zoom!",
    "dialog.gift_title6": "This free Zoom meeting has ended",
    "dialog.host_end_meeting": "تم إنهاء هذا الاجتماع من قبل المضيف",
    "dialog.host_end_webinar": "تم إنهاء هذا الويبينار من قبل المضيف",
    "dialog.meeting_ended": "انتهى الاجتماع",
    "dialog.meeting_locked": "تم إغلاق الاجتماع",
    "dialog.meeting_removed_by_host": "تمت إزالتك من هذا الاجتماع من قبل المضيف.",
    "dialog.newname": "اسم",
    "dialog.ok": "نعم",
    "dialog.presscode": "معرف المؤتمر",
    "dialog.rename": "إعادة تسمية",
    "dialog.server_error": "واجه الخادم خطأً داخليًا ولم يتمكن من معالجة طلبك.",
    "dialog.webinar_ended": "تم إنهاء الندوة عبر الإنترنت",
    "dialog.webinar_removed_by_host": "تمت إزالتك من هذا البرنامج التعليمي على الويب بواسطة المضيف.",
    "dialog.you_are_removed": "لقد تم إزالتك",
    "dialog_make_cohost": "هل تريد ان تجعل {{displayName}} المضيف البديل لهذا الاجتماع?",
    "dialog_make_host": "هل تريد ان تغير المضيف ل {{displayName}} ?",
    "dialog_remove_user": "هل تريد حذف {{displayName}}?",
    "disclaimer.LT_button_1": "من يمكنه رؤية هذا النص؟",
    "disclaimer.LT_content_1_1": "يمكن لمالك الحساب وكل شخص في الاجتماع حفظ هذا النص ومشاركته مع التطبيقات وغيرها.",
    "disclaimer.LT_content_2": "تم تمكين النسخ المباشر (الترجمة والشرح)",
    "disclaimer.QA_button_1": "من يمكنه رؤية أسئلتك؟",
    "disclaimer.QA_content_1_1": "سيتمكن مالك الحساب والمضيف وأعضاء اللجنة من معرفة هويتك ومعلومات الاتصال الخاصة بك (إذا قمت بتسجيل الدخول أو قدمتها) وسؤالك - ويمكن مشاركتها مع التطبيقات وغيرها.",
    "disclaimer.QA_content_2": "إذا تم تحديد سؤالك ، فسيكون مرئيًا لجميع الحاضرين.",
    "disclaimer.QA_content_3_3": "ما لم ترسل بشكل مجهول ، سيتمكن مالك الحساب والمضيف وأعضاء اللجنة من معرفة هويتك ومعلومات الاتصال الخاصة بك (إذا قمت بتسجيل الدخول أو قدمتها) وسؤالك - ويمكن مشاركتها مع التطبيقات وغيرها .",
    "disclaimer.QA_content_4": "هذه الأسئلة والأجوبة عامة ، حتى يتمكن الجميع من رؤية أسئلتك.",
    "disclaimer.QA_content_5": "إذا قمت بإرسال أسئلتك دون الكشف عن هويتك ، فلن يتمكن أحد من رؤية من أرسل أسئلتك.",
    "disclaimer.chat_button_normal": "من يمكنه رؤية رسائلك؟",
    "disclaimer.chat_button_onArchiving": "من يمكنه رؤية رسائلك؟ أرشفة",
    "disclaimer.chat_button_onRecording": "من يمكنه رؤية رسائلك؟ التسجيل قيد التشغيل",
    "disclaimer.chat_content_1": "يمكن لأي شخص في الاجتماع رؤية رسائلك وحفظها مع الجميع - ويمكنهم مشاركتها مع التطبيقات وغيرها.",
    "disclaimer.chat_content_2": "يمكنك أنت ومن تدردش معهم فقط حفظ رسائلك المباشرة ومشاركتها مع التطبيقات وغيرها.",
    "disclaimer.chat_content_3": "التسجيل قيد التشغيل ، لذلك يمكن لمالك الحساب وكل شخص في الاجتماع رؤية الرسائل المرسلة إلى الجميع وحفظها - ويمكنهم مشاركتها مع التطبيقات وغيرها.",
    "disclaimer.chat_content_4": "التسجيل قيد التشغيل ، حتى يتمكن كل شخص في الاجتماع من رؤية الرسائل المرسلة إلى الجميع وحفظها - ويمكنهم مشاركتها مع التطبيقات وغيرها.",
    "disclaimer.chat_content_5": "الأرشفة قيد التشغيل ، لذلك يمكن لمالك الحساب رؤية جميع رسائلك - بما في ذلك رسائلك المباشرة - ومشاركتها مع التطبيقات وغيرها.",
    "disclaimer.chat_content_6": "يمكن لأي شخص في الاجتماع حفظ الرسائل التي ترسلها إلى الجميع ومشاركتها.",
    "disclaimer.chat_content_7": "الأرشفة قيد التشغيل ، لذلك يمكن لمالك الحساب رؤية جميع رسائلك - باستثناء رسائلك المباشرة - ومشاركتها مع التطبيقات وغيرها.",
    "errorcodes_be_removed": "يتم إزالته.",
    "errorcodes_denied_email": "تم حظر البريد الإلكتروني من قبل المسؤول.",
    "errorcodes_denied_register_with_panelist": "رفض التسجيل استخدام البريد الإلكتروني أعضاء اللجنة.",
    "errorcodes_disconnect": "تم قطع الاتصال بالاجتماع.",
    "errorcodes_email_require": "البريد الإلكتروني مفقود لحضور الندوة عبر الإنترنت.",
    "errorcodes_fail": "فشل في الانضمام إلى الاجتماع.",
    "errorcodes_frequent_call": "لقد وصلت إلى الحد الأقصى لواجهة برمجة التطبيقات لهذه المكالمة.",
    "errorcodes_frequent_join": "أنت تحد عن طريق التكبير ، تحتاج إلى التحقق من recaptcha.",
    "errorcodes_login_required": "Don't support meeting/webinar authentication",
    "errorcodes_need_use_zoom_desktop_or_mobile": "تعذر الانضمام من المتصفح ، يرجى الانضمام باستخدام تطبيق Zoom لسطح المكتب أو تطبيق الهاتف المحمول.",
    "errorcodes_not_exist": "الاجتماع غير موجود.",
    "errorcodes_not_host": "أنت لست مضيف الاجتماع.",
    "errorcodes_not_init": "الاجتماع غير مهيأ.",
    "errorcodes_not_start": "لم يبدأ الاجتماع",
    "errorcodes_not_support_registration": "Don't support meeting/webinar registration",
    "errorcodes_offline": "الخدمة غير متصلة بالإنترنت مؤقتًا.",
    "errorcodes_pac_api_disabled": "مفتاح واجهة برمجة التطبيقات للحسابات غير مفعّل.",
    "errorcodes_pac_api_wrong": "مفتاح API للحسابات غير صالح.",
    "errorcodes_pac_cant_host_other_mn": "لا يمكن استضافة اجتماع آخر في نفس الوقت.",
    "errorcodes_pac_host_not_found": "لم يتم العثور على مضيف الاجتماع.",
    "errorcodes_pac_invalid_signature": "التوقيع غير صالح.",
    "errorcodes_pac_mn_not_fount": "لم يتم العثور على رقم الاجتماع.",
    "errorcodes_pac_mn_wrong": "رقم الاجتماع خاطئ.",
    "errorcodes_pac_no_permission": "لا يوجد إذن.",
    "errorcodes_pac_not_allow_assistant": "تم تعطيل انضمام المساعد إلى الاجتماع",
    "errorcodes_pac_role_error": "دور غير صحيح.",
    "errorcodes_pac_signature_expired": "انتهت صلاحية التوقيع.",
    "errorcodes_re_connect": "الاجتماع يعيد الاتصال.",
    "errorcodes_register": "هذا الاجتماع يتطلب التسجيل.",
    "errorcodes_rwc_empty": "تعذر الحصول على استجابة من خادم الويب.",
    "errorcodes_rwc_error": "تعذر الاتصال بخادم الويب خطأ.",
    "errorcodes_sign_webinar": "لا تدعم تسجيل الدخول إلى الويبينار",
    "errorcodes_success": "انضم إلى الاجتماع بنجاح.",
    "errorcodes_tk_expired": "انتهت صلاحية الرمز.",
    "errorcodes_wasm_fail": "خطأ في تنزيل ملفات wasm ، يرجى التحقق من الشبكة وجدار الحماية.",
    "errorcodes_web_has_in_progress": "بالفعل اجتماعات أخرى في التقدم.",
    "errorcodes_web_host_not_exit": "مضيف الاجتماع غير موجود.",
    "errorcodes_web_invalid_id": "معرف الاجتماع غير صالح.",
    "errorcodes_web_not_allow_start_webinar_from_web": "عدم السماح ببدء ندوة عبر الويب من الويب.",
    "errorcodes_web_not_support_registration_webinar": "لا تدعم التسجيل الندوة",
    "errorcodes_web_not_support_tsp": "لا تدعم بدء الاجتماع أو الانضمام إليه من الويب ، عندما تختار TSP كصوت له في الاجتماع.",
    "errorcodes_web_not_support_webclient": "لا يدعم بدء الاجتماع أو الانضمام إليه من الويب.",
    "errorcodes_web_not_support_webinar_pac": "لا تدعم ندوة الويب والمؤتمر الصوتي الشخصي",
    "errorcodes_web_require_email": "البريد الإلكتروني للمستخدم مطلوب.",
    "errorcodes_web_should_support_webinar_with_latest_version": "إصدار sdk الحالي لا يدعم البرنامج التعليمي على الويب ، يرجى الترقية إلى أحدث إصدار.",
    "errorcodes_wrong_pass": "رمز مرور الاجتماع خاطئ.",
    "gallary_view": "عرض المعرض",
    "getty.content_webinar_1": "Participants with relevant permissions also may save and share the webinar transcript.",
    "invalid_parameter": "معلمة غير صالحة",
    "invite.loading": "تحميل...",
    "join_btn_join": "انضمام",
    "meeting_add_pin": "إضافة دبوس",
    "meeting_disconnected": "الاجتماع غير متصل",
    "meeting_info": "معلومات الاجتماع",
    "meeting_info_network": "You are connected to {{network}} via data centers in {{dc}}",
    "meeting_not_start": "الاجتماع لم يبدأ",
    "meeting_remove_pin": "إزالة الدبوس",
    "meeting_replace_pin": "استبدال دبوس",
    "meeting_taking": "تتحدث:",
    "meeting_waiting_for_start": "بانتظار بدأ الاجتماع",
    "meeting_waiting_room": "سيقوم المضيف بادخالك قريبا",
    "minimized_view": "Minimized",
    "mirror_my_video": "عكس الفيديو الخاص بي",
    "newLTT.ENABLE_MANUAL_CAPTIONER": "Enable manual captioner",
    "newLTT.caption_settings": "Caption settings",
    "newLTT.hide_captions": "Hide captions",
    "newLTT.host_controls": "Host controls",
    "newLTT.live_transcript": "Live Transcript",
    "newLTT.manual_caption_describe": "In Manage Participants panel, hover on a participant; in the \"More\" menu, select \"Assign to Type Closed Caption\".",
    "newLTT.more": "More",
    "newLTT.set_up_manual_captioner": "Set up manual captioner",
    "newLTT.show_captions": "Show captions",
    "newLTT.show_captions_window": "Show Captions Window",
    "newLTT.show_original_and_translated": "Show original and translated",
    "newLTT.speaking_language": "Speaking language:",
    "newLTT.transcription_language": "Transcription language:",
    "newLTT.translate_to": "Translate to",
    "newLTT.view_full_transcript": "View full transcript",
    "newLTT.your_caption_settings": "Your caption settings",
    "non_verbal.i_am_away": "I'm away",
    "non_verbal.i_am_back": "I'm back",
    "non_verbal.no": "لا",
    "non_verbal.slow_down": "ابطئ",
    "non_verbal.speed_up": "اسرع",
    "non_verbal.yes": "نعم",
    "polling.Back": "خلف",
    "promote.cancel": "كن حاضرًا",
    "promote.content_1": "بصفتك عضوًا في اللجنة ، يمكنك إلغاء كتم الصوت وبدء تشغيل الفيديو مما يعني أنك ستكون مرئيًا للآخرين في ندوة الويب.",
    "promote.content_3_2": "If the host or panelists decide to record, livestream, or archive the webinar after you unmute, your participation will be included. If the webinar is recorded it may be shared with Smart Recording which uses AI technology, which may include third-party models. Zoom does not use any audio, video, chat, screen sharing, attachments or other communications-like content (such as poll results, whiteboard and reactions) to train Zoom’s or third-party AI models.",
    "promote.ok": "انضم كعضو في اللجنة",
    "promote.title": "يرغب المضيف في ترقيتك لتكون عضوًا في اللجنة",
    "reaction.clap": "التصفيق",
    "reaction.heart": "قلب",
    "reaction.joy": "مرح",
    "reaction.more": "أكثر",
    "reaction.open_mouth": "فتح الفم",
    "reaction.tada": "ثم",
    "reaction.thumbs_up": "ممتاز",
    "reaction.unknown": "مجهول",
    "ribbon_view": "Ribbon",
    "rmc.assistant_exist_warning": "لا يمكنك التحكم في الاجتماع لأن مساعدًا آخر يتحكم في هذا الاجتماع.",
    "rmc.exist_notification_for_client_host": "يتم التحكم في هذا الاجتماع من قبل المسؤول.",
    "rmc.not_exist_notification_for_client_host": "توقف المسؤول عن التحكم في الاجتماع.",
    "same_as_system": "مثل النظام",
    "security.allow_participants_to": "اسمح للمشاركين بـ:",
    "security.button": "حماية",
    "security.waiting_room": "تفعيل غرفة الانتظار",
    "select_allow": "Select the option Allow.",
    "settings": "إعدادات",
    "settings.audio_tab_text": "Audio",
    "settings.enable_hd": "",
    "settings.enable_hd_tip": "",
    "settings.frame_per_second": "Frame Per Second",
    "settings.frequency": "Frequency",
    "settings.input_level": "Input Level:",
    "settings.item_name": "Item name",
    "settings.jitter": "Jitter",
    "settings.latency": "Latency",
    "settings.maximum_view": "Maximum participants displayed per screen in Gallery View:",
    "settings.output_level": "Output level",
    "settings.packet_loss": "Packet Loss - Avg(Max)",
    "settings.participants25": "25 participants",
    "settings.participants9": "9 participants",
    "settings.playing": "Playing",
    "settings.receive": "Receive",
    "settings.receiving_video": "",
    "settings.receiving_video_tips": "",
    "settings.recording": "Recording",
    "settings.rejoin": "",
    "settings.resolution": "Resolution",
    "settings.send": "Send",
    "settings.sending_video": "",
    "settings.sending_video_tips": "",
    "settings.share_tab_text": "Screen Sharing",
    "settings.statistics": "Statistics",
    "settings.stop": "Stop",
    "settings.switch_view_mode_text": "",
    "settings.test_mic": "Test Mic",
    "settings.test_speaker": "Test Speaker",
    "settings.unknown_device": "Unknown device",
    "settings.use_hardware_acceleration": "",
    "settings.vb_init_10s_tip2": "Virtual Background is taking longer than expected to load.",
    "settings.vb_init_fail2": "Unable to load Virtual Background.",
    "settings.video_tab_text": "Video",
    "smartSummary.enable_content_1_2": "Meeting Summary uses AI technology, which may include third-party models. Zoom does not use any audio, video, chat, screen sharing, attachments or other communications-like content (such as poll results, whiteboard and reactions) to train Zoom’s or third-party AI models.",
    "smartSummary.enable_content_2_2": "We’ll send the meeting summary to invitees after the meeting ends (based on the settings configured for this meeting). Anyone who receives the meeting summary may save and share it with apps and others. The account owner can access the meeting summary.",
    "smartSummary.enable_content_3": "AI-generated content may be inaccurate or misleading. Always check for accuracy.",
    "smartSummary.enabled": "Meeting Summary has been enabled",
    "smartSummary.info_2": "A summary of this meeting and next steps is being automatically generated.",
    "smartSummary.start_smart_summary": "Start Summary",
    "smartSummary.stop_smart_summary": "Stop Summary",
    "smartSummary.toast_button_description_text": "The summary from this meeting may be saved and shared with apps and others by participants with relevant permissions (based on the settings configured for this meeting).",
    "smartSummary.toast_button_text": "Who can see this summary?",
    "smartSummary.toast_text_1": "Meeting Summary with Zoom IQ on.",
    "smartSummary.toast_text_2": "Meeting Summary with Zoom IQ stopped",
    "speaker_view": "عرض المتحدث",
    "toolbar_ask_unmute": "اطلب إلغاء كتم الصوت",
    "toolbar_join_audio": "انضمام الصوت",
    "toolbar_leave": "مغادرة",
    "toolbar_mute": "كتم الصوت",
    "toolbar_muteall": "كتم الكل",
    "toolbar_record": "سِجِلّ",
    "toolbar_unmute": "تشغيل الصوت",
    "transcription.Arabic": "Arabic",
    "transcription.Bengali": "Bengali",
    "transcription.Chinese": "Chinese (Simplified)",
    "transcription.Chinese_Traditional": "Chinese (Traditional)",
    "transcription.Czech": "Czech",
    "transcription.Dutch": "Dutch",
    "transcription.English": "English",
    "transcription.Estonian": "Estonian",
    "transcription.Finnish": "Finnish",
    "transcription.French": "French",
    "transcription.German": "German",
    "transcription.Greek": "Greek",
    "transcription.Hebrew": "Hebrew",
    "transcription.Hindi": "Hindi",
    "transcription.Hungarian": "Hungarian",
    "transcription.Indonesian": "Indonesian",
    "transcription.Italian": "Italian",
    "transcription.Japanese": "Japanese",
    "transcription.Korean": "Korean",
    "transcription.Malay": "Malay",
    "transcription.Persian": "Persian",
    "transcription.Polish": "Polish",
    "transcription.Portuguese": "Portuguese",
    "transcription.Reserved": "Reserved",
    "transcription.Romanian": "Romanian",
    "transcription.Russian": "Russian",
    "transcription.Spanish": "Spanish",
    "transcription.Swedish": "Swedish",
    "transcription.Tagalog": "Tagalog",
    "transcription.Tamil": "Tamil",
    "transcription.Telugu": "Telugu",
    "transcription.Turkish": "Turkish",
    "transcription.Ukrainian": "Ukrainian",
    "transcription.Vietnamese": "Vietnamese",
    "video.remove_all_pins": "قم بإزالة كافة الدبابيس",
    "video.remove_all_spotlights": "إزالة كافة الأضواء",
    "wait_room_tip1": "لقد دخل {0} إلى غرفة الانتظار لهذا الاجتماع",
    "wait_room_tip2": "دخل {0} من الأشخاص إلى غرفة انتظار هذا الاجتماع",
    "wc.ast_admin_name": "مساعد الاجتماع",
    "wc.off": "Off",
    "wc.on": "On",
    "wc.rmc_admin_name": "إدارة التحكم في الاجتماع",
    "wc.rmc_admin_tooltip": "يمتلك هذا المستخدم عناصر تحكم مضيفة ولا يمكنه الوصول إلى أي محتوى وسائط (صوت وفيديو ودردشة وردود فعل).",
    "wc_3rd_cc_copied_api_token": "The API token has been copied to your clipboard",
    "wc_3rd_cc_copy_api_token": "Copy the API token",
    "wc_3rd_cc_service": "استخدم خدمة نسخة خارجية",
    "wc_3rd_cc_url_help_tips2": "Copy this token and paste it in a 3rd-party Closed Captioning tool",
    "wc_admit": "قبول",
    "wc_allow_to_talk": "اسمح للحديث",
    "wc_audio": "صوتي",
    "wc_audio.muted_notification1": "كتم المضيف صوتك",
    "wc_audio.muted_notification2": "كتم المضيف صوت الجميع",
    "wc_audio.unmute_by_host_content_1": "يود المضيف أن تتحدث",
    "wc_audio.unmute_by_host_content_6_2": "If you choose to unmute, others in the webinar will be able to hear you. If the host or panelists decide to record, livestream, or archive the webinar after you unmute, your voice will be included. If the webinar is recorded it may be shared with Smart Recording which uses AI technology, which may include third-party models. Zoom does not use any audio, video, chat, screen sharing, attachments or other communications-like content (such as poll results, whiteboard and reactions) to train Zoom’s or third-party AI models.",
    "wc_audio.unmuted_by_host_content": "يرغب المضيف في إلغاء كتم الصوت",
    "wc_audio_cannot_unmute": "لا يمكنك إعادة الصوت لأن المضيف كتم صوتك.",
    "wc_audio_connecting_thumbnail": "Connecting to audio",
    "wc_audio_setting": "ضبط الصوت",
    "wc_bo.addroom": "أضف غرفة",
    "wc_bo.all_room_will_close_sdk": "All Breakout Rooms will close in {{countdown}} seconds.",
    "wc_bo.all_room_will_close_tips": "ستتم إعادتك إلى الجلسة الرئيسية تلقائيًا.",
    "wc_bo.assign": "تعيين",
    "wc_bo.assign_rooms_2_sdk": "Create {{num_bo_rooms}} breakout rooms",
    "wc_bo.assign_rooms_3_sdk": "Recreate {{num_bo_rooms}} breakout rooms",
    "wc_bo.assign_to": "يسند إلى",
    "wc_bo.breakout_rooms": "غرف جانبية",
    "wc_bo.broadcast": "إذاعة",
    "wc_bo.broadcast_message_to_all2": "إرسال رسالة للجميع",
    "wc_bo.close_all_rooms": "أغلق جميع الغرف",
    "wc_bo.create_room_window_title": "إنشاء غرف جانبية",
    "wc_bo.current_room_will_close_sdk": "Breakout Rooms will close in {{countdown}} seconds.",
    "wc_bo.delete_room_confirm_tip_sdk": "Delete {{roomName}}?",
    "wc_bo.distrubution_auto_assign": "التعيين تلقائيًا",
    "wc_bo.distrubution_manually_assign": "تعيين يدويًا",
    "wc_bo.in_progress": "في تَقَدم",
    "wc_bo.join_room": "انضم إلى غرفة الاستراحة",
    "wc_bo.join_room__confirm_tip_sdk": "Join {{roomName}}?",
    "wc_bo.join_room_tip_content2": "لقد تم تعيينك ل",
    "wc_bo.joined": "انضم",
    "wc_bo.message_all_rooms": "مراسلة جميع الغرف ...",
    "wc_bo.moveto": "الانتقال إلى",
    "wc_bo.no_unassigned_tip": "تم تعيين جميع المشاركين في غرف الاجتماعات الفرعية.",
    "wc_bo.not_joined": "غير منضم",
    "wc_bo.not_now": "ليس الآن",
    "wc_bo.not_started": "لم يبدأ",
    "wc_bo.open_all_rooms": "افتح كل الغرف",
    "wc_bo.options_alllowreturn": "اسمح للمشاركين بالعودة إلى الجلسة الرئيسية في أي وقت",
    "wc_bo.options_automove": "انقل جميع المشاركين المعينين تلقائيًا إلى غرف الاستراحة",
    "wc_bo.options_closeroom_auto": "إغلاق تلقائي للغرف الجانبية بعد {0} دقيقة",
    "wc_bo.options_countdowntime": "ضبط مؤقت العد التنازلي: {0} ثانية",
    "wc_bo.options_needcountdown": "العد التنازلي بعد إغلاق غرفة الاستراحة",
    "wc_bo.options_timeupnotify": "أعلمني عندما يحين الوقت",
    "wc_bo.perroom_size_sdk": "{{num_per_room}} participants per room",
    "wc_bo.recreate": "إعادة",
    "wc_bo.return_to_main_sessoin": "العودة إلى الجلسة الرئيسية",
    "wc_bo.unassigned": "غير معين",
    "wc_broadcasting": "البث",
    "wc_btn_endconf_meeting_all": "إنهاء الاجتماع للجميع",
    "wc_camera_prevent": "متصفحك يمنع الوصول إلى الكاميرا الخاصة بك. يرجى تمكينه وإعادة تشغيل الفيديو الخاص بك",
    "wc_cc.placeholder": "اكتب هنا ، واضغط على Enter للبث",
    "wc_cc_assign_participant_to_type": "قم بتعيين مشارك للكتابة",
    "wc_cc_assign_to": "تعيين لكتابة تسمية توضيحية مغلقة",
    "wc_cc_assign_to_type": "كلف شخصًا بالكتابة",
    "wc_cc_broadcasting_tip": "Closed Captions are being broadcast to all participants.",
    "wc_cc_host_assigned": "لقد عيّنك المضيف لكتابة تسمية توضيحية مغلقة",
    "wc_cc_type_myself": "سأكتب",
    "wc_cc_withdraw": "سحب إذن الترجمة والشرح",
    "wc_chat.allow_chat_with_meeting": "يمكن للمشارك الدردشة مع:",
    "wc_chat.attendee_chat_with": "يمكن للحاضر الدردشة مع:",
    "wc_chat.chat": "محادثة",
    "wc_chat.direct_message": "(رسالة مباشرة)",
    "wc_chat.disabled": "لا احد",
    "wc_chat.everyone": "الجميع",
    "wc_chat.everyone_directly": "الجميع وأي شخص بشكل مباشر",
    "wc_chat.host_co_hosts": "المضيف والمضيفون المشاركون",
    "wc_chat.host_panelists": "المضيفون وأعضاء اللجنة",
    "wc_chat.me": "أنا",
    "wc_chat.panelist_chat_with": "يمكن لأعضاء اللجنة الدردشة مع:",
    "wc_chat.type_msg": "اكتب الرسالة هنا ...",
    "wc_closed_caption_btn": "تسمية توضيحية مغلقة",
    "wc_co_host": "(مضيف مشارك)",
    "wc_continue": "يكمل",
    "wc_copied": "نسخ",
    "wc_copied_to_clipboard": "تم نسخ رابط الدعوة إلى الحافظة",
    "wc_copy_link": "نسخ الوصلة",
    "wc_data_center2": "أنت متصل بمركز بيانات محلي.",
    "wc_data_center3": "أنت متصل بشبكة Zoom العالمية عبر مركز بيانات محلي.",
    "wc_disable_talking": "تعطيل التحدث",
    "wc_dlg_confirm": "تأكيد",
    "wc_enable": "ممكن",
    "wc_encryption": "التشفير",
    "wc_extra_function_disable_video": "تعطيل استقبال الفيديو",
    "wc_files": "الملفات",
    "wc_footer_assign_leave": "التعيين والمغادرة",
    "wc_footer_assign_new_host": "قم بتعيين مضيف جديد",
    "wc_guest": "ضيف",
    "wc_host_1": "المضيف",
    "wc_in_the_meeting": "في الاجتماع",
    "wc_invite_link": "دعوة الارتباط",
    "wc_join_media_preview_info_confirm": "فهمتها",
    "wc_join_media_preview_warning_denied_both": "قم بتمكين الوصول إلى الكاميرا والميكروفون في شريط عنوان المتصفح.",
    "wc_join_media_preview_warning_denied_camera": "قم بتمكين الوصول إلى الكاميرا في شريط عنوان المتصفح الخاص بك.",
    "wc_join_media_preview_warning_denied_mic": "قم بتمكين الوصول إلى الميكروفون في شريط عنوان المتصفح.",
    "wc_joining": "انضمام",
    "wc_joining_meeting": "... جار الانضمام إلى الاجتماع",
    "wc_learn_more": "يتعلم أكثر",
    "wc_leave_bo_room": "اترك غرفة الإستراحة",
    "wc_leave_computer_audio": "اترك صوت الكمبيوتر",
    "wc_leave_meeting": "مغادرة الاجتماع",
    "wc_leave_webinar": "اترك البرنامج التعليمي على الويب",
    "wc_live_transcription_btn": "النسخ المباشر",
    "wc_lock_meeting": "إقفال الاجتماع",
    "wc_lower_hand": "اليد السفلى",
    "wc_lt_disable_transcription": "تعطيل النسخ التلقائي",
    "wc_lt_enable_transcription": "تمكين النسخ التلقائي",
    "wc_lt_header": "نص",
    "wc_lt_item_captioner": "(التسمية التوضيحية)",
    "wc_lt_live_transcript": "النسخ المباشر",
    "wc_lt_menu_item1": "إظهار الترجمة",
    "wc_lt_menu_item2": "مشاهدة النسخة كاملة",
    "wc_lt_menu_item3": "إخفاء الترجمة",
    "wc_lt_menu_item4": "إغلاق النسخة الكاملة",
    "wc_lt_request_host_ctrl": "Allow participants to request Live Transcription",
    "wc_lt_search_text": "يبحث",
    "wc_make_co_host": "اجعل مضيفًا مشاركًا",
    "wc_make_host": "اجعل المضيف",
    "wc_me": "(أنا)",
    "wc_more": "أكثر",
    "wc_no": "لا",
    "wc_none": "لا أحد",
    "wc_not_share_pronoun": "Don't Share",
    "wc_num_password": "رقم الهاتف كلمة السر / أنظمة الغرف",
    "wc_optimize_for_video_clip": "Optimize for video clip",
    "wc_participant_id": "معرف المشارك",
    "wc_participants": "المشاركون",
    "wc_pc_audio": "صوت الكمبيوتر",
    "wc_prevent_access_mic": "متصفحك يمنع الوصول إلى الميكروفون الخاص بك.",
    "wc_prevent_access_share": "يرجى منح المتصفح حق الوصول إلى تسجيل الشاشة.",
    "wc_put_in_waiting": "ضع في غرفة الانتظار",
    "wc_qa.allQ": "كل الأسئلة",
    "wc_qa.anonymous_attendee": "حضور مجهول",
    "wc_qa.answer_private_type": "إجابة خاصة",
    "wc_qa.answeredQ": "أجاب",
    "wc_qa.attendee_placeholder": "Questions you ask the host and panelists will show up here.",
    "wc_qa.button_comment": "تعليق",
    "wc_qa.button_display_answer": "اكتب الاجابة",
    "wc_qa.button_live": "الإجابة مباشرة",
    "wc_qa.button_live_done": "منتهي",
    "wc_qa.button_reopen": "أعد فتح",
    "wc_qa.collapse_all_answer": "انهيار جميع",
    "wc_qa.dismissedQ": "مرفوض",
    "wc_qa.display_all_answer": "عرض الكل",
    "wc_qa.dissmis_tips": "رفض",
    "wc_qa.input_tips": "اكتب سؤالك هنا...",
    "wc_qa.is_anonymous": "إرسال مجهول",
    "wc_qa.is_privately": "أرسل بشكل خاص",
    "wc_qa.live_tips_done": "تم الرد على هذا السؤال مباشرة",
    "wc_qa.live_tips_start": "يود أن يجيب على هذا السؤال مباشرة",
    "wc_qa.most_recent": "Most Recent",
    "wc_qa.most_upvotes": "Most Upvotes",
    "wc_qa.myQ": "أسئلتي",
    "wc_qa.no_answered_questions": "No answered questions",
    "wc_qa.no_dismissed_questions": "No dismissed questions",
    "wc_qa.no_open_questions": "No open questions",
    "wc_qa.no_questions": "No questions",
    "wc_qa.openedQ": "يفتح",
    "wc_qa.panelist_host_only_placeholder": "Only hosts and panelists can see the questions",
    "wc_qa.panelist_view_all_placehoder": "Everyone in this webinar can see open questions",
    "wc_qa.qa_comp_title": "سؤال وجواب",
    "wc_qa.send": "يرسل",
    "wc_qa.setting_allow_view": "السماح للحاضرين بالعرض",
    "wc_qa.setting_btn_name": "إعدادات",
    "wc_qa.setting_option_allow_anony_question": "السماح الأسئلة مجهولة المصدر",
    "wc_qa.setting_option_allow_comment": "يمكن للحاضرين التعليق",
    "wc_qa.setting_option_allow_view_all": "كل الأسئلة",
    "wc_qa.setting_option_allow_view_answered": "أجاب على الأسئلة فقط",
    "wc_qa.setting_option_allow_vote": "يمكن للحاضرين التصويت",
    "wc_qa.welcome_banner": "لا تتردد في طرح أسئلة على المضيف وأعضاء اللجنة",
    "wc_qa.welcome_banner_title": "مرحباً",
    "wc_raise_hand": "رفع اليد",
    "wc_reactions": "تفاعلات",
    "wc_reclaim_host": "استعادة المضيف",
    "wc_record_host_reminder_desc": "By continuing, all faces, conversations, and screen sharing will be recorded to the cloud.",
    "wc_record_local_allow_btn": "Allow Recording",
    "wc_record_local_deny_btn": "Deny",
    "wc_record_local_denyed": "Request to record denied by Host",
    "wc_record_local_granted": "Request to record granted by Host",
    "wc_record_local_request_tip": "Apply these permissions to all future requests",
    "wc_record_local_request_title": "{{displayName}} is requesting to record this meeting locally",
    "wc_record_reminder_desc": "من خلال الاستمرار في التواجد في الاجتماع ، فإنك توافق على أن يتم تسجيلك.",
    "wc_record_reminder_desc_2": "يمكن لـ {0} والمضيف مشاهدة تسجيلات Zoom Cloud ويمكن لأي مشارك لديه إذن التسجيل على أجهزته المحلية. يمكن لهؤلاء الأفراد مشاركة هذه التسجيلات مع التطبيقات وغيرها.",
    "wc_record_reminder_title": "يتم تسجيل هذا الاجتماع",
    "wc_record_reminder_webinar_title": "يتم تسجيل هذه الندوة عبر الإنترنت",
    "wc_record_webinar_reminder_desc": "من خلال الاستمرار في التواجد في الندوة عبر الإنترنت ، فإنك توافق على أن يتم تسجيلك.",
    "wc_record_with_zoom_iq": "With Zoom IQ",
    "wc_recording_pause": "وقفة التسجيل",
    "wc_recording_resume": "استئناف التسجيل",
    "wc_recording_stop": "إيقاف التسجيل",
    "wc_recording_title": "Record this meeting?",
    "wc_remove": "إزالة",
    "wc_security.privacy_legal_policies": "Privacy & Legal Policies",
    "wc_select_camera": "حدد الكاميرا",
    "wc_select_microphone": "حدد ميكروفون",
    "wc_select_speaker": "اختر مكبر الصوت",
    "wc_share_muted_while_sharing_audio_tip2": "تم تعطيل الميكروفون عند مشاركة صوت الكمبيوتر. عند إيقاف مشاركة الصوت مؤقتًا أو إيقافها ، سيتم إعادة تنشيط الميكروفون.",
    "wc_share_pronoun": "Share",
    "wc_share_pronoun_menu": "Share My Pronouns",
    "wc_share_pronoun_tip2": "Would you like to share your pronouns in this meeting?",
    "wc_sharer_controlbar_container_button3_label": "وقف المشاركة",
    "wc_sharer_controlbar_container_rec_status_tip1": "أنت تشارك الشاشة",
    "wc_sharer_controlbar_container_rec_status_tip2": "تم إيقاف مشاركة شاشتك مؤقتًا",
    "wc_sharer_disabled_share1_desc": "استضافة مشاركة شاشة الحضور المعطلة.",
    "wc_sharer_disabled_share2_desc": "لا يمكنك بدء مشاركة الشاشة أثناء مشاركة المشارك الآخر.",
    "wc_sharer_entry_button_label1": "شاشة المشاركة",
    "wc_sharer_setting_menu_category1_title": "من يمكنه المشاركة؟",
    "wc_sharer_setting_menu_category2_title": "من يمكنه بدء المشاركة عندما يشارك شخص آخر؟",
    "wc_sharer_setting_menu_category3_title": "كم عدد المشاركين الذين يمكنهم المشاركة في نفس الوقت؟",
    "wc_sharer_setting_menu_category_option1": "المضيف الوحيد",
    "wc_sharer_setting_menu_category_option2": "جميع المشاركين",
    "wc_sharer_setting_menu_item1": "يمكن لمشارك واحد المشاركة في كل مرة",
    "wc_sharer_setting_menu_item2": "يمكن لعدة مشاركين المشاركة في وقت واحد",
    "wc_sharing_fit_to_window": "تناسب النافذة",
    "wc_sharing_original_size": "الحجم الأصلي",
    "wc_sharing_shared_screens": "الشاشات المشتركة",
    "wc_sharing_view_options": "عرض الخيارات",
    "wc_sharing_viewing": "أنت تشاهد شاشة {0}",
    "wc_tel_password": "رمز عبور",
    "wc_unmute_by_host_btn1": "ابق صامتًا",
    "wc_unmute_by_host_btn3": "أعد صوتي",
    "wc_unmute_by_host_content2": "قام المضيف بتسليط الضوء على الفيديو الخاص بك للجميع. هل ترغب في إعادة صوت الميكروفون للتحدث؟",
    "wc_unmute_by_host_content3": "قام المضيف بتسليط الضوء على الفيديو الخاص بك للجميع. هل ترغب في الانضمام إلى الصوت للتحدث؟",
    "wc_unshare_pronoun_menu": "Unshare My Pronouns",
    "wc_video.allow_panelist_start_video": "السماح لأعضاء اللجنة ببدء الفيديو",
    "wc_video.allow_participants_start_video": "Allow participants to start video",
    "wc_video.ask_start_video": "اطلب بدء الفيديو",
    "wc_video.later": "لاحقاً",
    "wc_video.model_start": "لقد طلب منك المضيف أن تبدأ الفيديو الخاص بك",
    "wc_video.model_stop": "لا يمكنك بدء الفيديو الخاص بك لأن المضيف أوقفه",
    "wc_video.remove_spotlight": "إزالة Spotlight",
    "wc_video.replace_spotlight": "استبدل Spotlight",
    "wc_video.spotlight_for_everyone": "تسليط الضوء على الجميع",
    "wc_video.start_my_video": "ابدأ الفيديو الخاص بي",
    "wc_video.start_video": "تشغيل الفيديو",
    "wc_video.stop_video": "إيقاف الفيديو",
    "wc_video.video": "فيديو",
    "wc_view": "عرض",
    "wc_waiting_room": "غرفة الانتظار",
    "wc_wc_remove_all_pin_desc": "سيؤدي تمييز {0} الجميع إلى إزالة جميع مقاطع الفيديو المثبتة ، هل تريد المتابعة؟",
    "wc_wc_remove_all_spotlight_desc": "سيؤدي تثبيت {0} للجميع إلى إزالة كافة مقاطع الفيديو المميزة ، هل تريد المتابعة؟",
    "wc_webinar.change_to_attendee": "تغيير الدور إلى الحاضر",
    "wc_webinar.promote_to_panelist": "قم بالترقية إلى عضو اللجنة",
    "wc_webinar_attendees": "الحاضرين",
    "wc_webinar_panelists": "المتحدثون",
    "wc_webinar_practice_broadcast_desc": "وضع الممارسة فقط: لا يمكن للحاضرين الانضمام حتى تقوم بالبث",
    "wc_webinar_practice_broadcast_new": "Start Webinar",
    "wc_webinar_practice_broadcast_status_tip": "يتم الآن بث الندوة عبر الويب لجميع الحاضرين",
    "wc_webinar_putonhold": "ضعه على الانتظار",
    "wc_withdraw_co_host": "سحب إذن المضيف المشترك",
    "wc_yes": "نعم",
    "websdk.active_view": "Active",
    "websdk_enforce_update_content": "يجب أن يكون إصدار تطبيقك {0} أو أعلى للانضمام إلى هذا الاجتماع. يرجى التحديث للمتابعة.",
    "websdk_update_content": "قم بتحديث WebSDK إلى أحدث إصدار لتحسين تجربة الاجتماع",
    "LS.content_1": "من خلال البقاء في هذا الاجتماع ، فإنك توافق على البث المباشر.",
    "LS.content_2": "يمكن لأي شخص لديه حق الوصول إلى البث المباشر المشاهدة أو المشاركة مع الآخرين.",
    "LS.title": "يجري بث هذا الاجتماع على الهواء مباشرة",
    "LS.toast": "يتم بث هذه الندوة عبر الإنترنت مباشرة",
    "about.text": "عن",
    "account_owners": "صاحب (أصحاب) الحساب",
    "allow_to_multi_pin": "السماح ل Multi-pin",
    "app_signal.another_people": "شعب آخر",
    "app_signal.other_people": "أشخاص أخرون",
    "app_signal.tip_text": "تتمتع التطبيقات بإمكانية الوصول في الوقت الفعلي إلى معلوماتك في هذا الاجتماع",
    "app_signal.used_by": "استعمل من قبل",
    "archiving.content1": "يخضع واحد أو أكثر من المشاركين في هذا الاجتماع للأرشفة بناءً على سياسة حساباتهم. سيتلقى {0} محتوى من هذا الاجتماع ويمكنه مشاركته مع التطبيقات وغيرها.",
    "archiving.content2": "من خلال البقاء في هذا الاجتماع ، فإنك توافق على أرشفة {0} هذا الاجتماع.",
    "archiving.fail_content": "يجب أرشفة {0} هذا الاجتماع لأغراض الامتثال.",
    "archiving.host_content": "يجب أرشفة {0} هذا الاجتماع لأغراض الامتثال.",
    "archiving.host_title": "انتهى هذا الاجتماع بسبب فشل الأرشفة",
    "archiving.participants_title": "تم قطع اتصالك بالاجتماع بسبب فشل الأرشفة",
    "archiving.subjects_combo_2": "{0} و {1}",
    "archiving.subjects_combo_3": "{0} و {1} و {2}",
    "archiving.subjects_combo_4": "{0} و {1} و {2} و {3}",
    "archiving.tips_1": "تتم أرشفة {0} هذا الاجتماع بواسطة مؤسسة المضيف بناءً على سياسة حساباتهم. سيتلقى {1} محتوى من هذا الاجتماع ويمكنه مشاركته مع التطبيقات وغيرها.",
    "archiving.tips_2": "تتم أرشفة {0} هذا الاجتماع بواسطة مؤسسة المضيف بناءً على سياسة حساباتهم. سيتلقى {1} محتوى من هذا الاجتماع ويمكنه مشاركته مع التطبيقات وغيرها.",
    "archiving.toast": "يتم أرشفة هذه الندوة عبر الإنترنت",
    "auth_fail": "المصادقة تفشل",
    "browser_share_dont_support_browser": "قد لا يدعم إصدار المتصفح الذي تستخدمه الميزة التالية. الرجاء الترقية إلى أحدث إصدار وحاول مرة أخرى.",
    "cant_skip_captcha": "لا يمكنك تخطي فحص captcha",
    "captcha": "كلمة التحقق",
    "captcha_checking_content": "يرجى التحقق من كلمة التحقق",
    "check_captcha": "تحقق من Captcha",
    "common.attendee_view": "عرض الحضور",
    "common.close": "إغلاق",
    "common.enable": "يُمكَِن",
    "common.follow_host_view": "اتبع وجهة نظر المضيف",
    "common.my_view": "وجهة نظري",
    "common.request": "طلب",
    "common.show_non_video_participants": "إظهار المشاركين غير الفيديو",
    "common.show_self_view": "إظهار العرض الذاتي",
    "common.standard": "معيار",
    "common.start": "يبدأ",
    "common.swap_video_and_shared_screen": "تبديل الفيديو والشاشة المشتركة",
    "common.you": "أنت",
    "confirm": "يتأكد",
    "copy_link_or_tk": "يرجى نسخ ارتباط الانضمام أو المعارف التقليدية من بريدك الإلكتروني",
    "copy_tk_link": "انسخ رابط الانضمام من البريد الإلكتروني والصقه أدناه",
    "dialog.btn_callme": "اتصل بي",
    "dialog.btn_callme_connected": "اتصل بي - متصل",
    "dialog.btn_endconf_meeting": "الاجتماع الختامي",
    "dialog.btn_exit": "خروج",
    "dialog.btn_hangup": "تعليق",
    "dialog.btn_merge": "دمج",
    "dialog.btn_save": "حفظ",
    "dialog.call_your_number": "اتصل برقم هاتفك للانضمام إلى المؤتمر الصوتي",
    "dialog.calling_indication": "كنت تتصل بـ {0} الآن. سوف ينضم إلى المؤتمر قريبًا جدًا.",
    "dialog.claim_host": "مضيف المطالبة",
    "dialog.claim_host_error_tips": "مفتاح المضيف الذي أدخلته غير صالح",
    "dialog.claim_host_helpful_tips": "يتكون مفتاح المضيف من 6 إلى 10 أرقام",
    "dialog.claim_host_title": "أدخل مفتاح المضيف للمطالبة بدور المضيف",
    "dialog.claim_host_verify": "جاري التحقق من مفتاح المضيف ...",
    "dialog.conference_ended": "انتهى المؤتمر",
    "dialog.dial_in": "اطلب بناءً على موقعك",
    "dialog.end_meeting": "أنهِ هذا الاجتماع",
    "dialog.end_meeting_confirm": "هل أنت متأكد أنك تريد إنهاء هذا الاجتماع الآن؟",
    "dialog.error_code": "خطا بالكود:",
    "dialog.expel_confirm": "هل أنت متأكد أنك تريد طرد {0} من المؤتمر؟",
    "dialog.hangup_confirm": "هل أنت متأكد أنك تريد قطع الاتصال بالصوت؟",
    "dialog.host_end_conference": "تم إنهاء هذا المؤتمر من قبل المضيف.",
    "dialog.invite_others": "ادعُ مشاركًا آخر",
    "dialog.leave_meeting": "اترك هذا الاجتماع",
    "dialog.leave_meeting_confirm": "هل أنت متأكد أنك تريد مغادرة هذا الاجتماع الآن؟",
    "dialog.leave_webinar": "اترك هذا البرنامج التعليمي على الويب",
    "dialog.leave_webinar_confirm": "هل أنت متأكد أنك تريد مغادرة هذا البرنامج التعليمي على الويب الآن؟",
    "dialog.lock_meeting": "إقفال الاجتماع",
    "dialog.lock_meeting_confirm": "هل أنت متأكد أنك تريد قفل هذا الاجتماع الآن؟",
    "dialog.meeting_cannot_join_locked": "لا يمكنك الانضمام إلى هذا الاجتماع الآن لأن المضيف أقفله.",
    "dialog.meeting_lock_prevent_join": "سيؤدي القفل إلى منع أي أشخاص آخرين من الانضمام إلى الاجتماع.",
    "dialog.meeting_over": "سيتم فصل جميع الموجودين في المكالمة وسينتهي الاجتماع.",
    "dialog.network_error": "خطأ في الشبكة ، يرجى المحاولة مرة أخرى.",
    "dialog.or": "أو",
    "dialog.placeholder_display_name": "الاسم الذي سيتم عرضه في الاجتماع",
    "dialog.placeholder_phone_number": "رقم التليفون",
    "dialog.remain_view": "سيتم قطع اتصالك بالصوت وستبقى كمشاهد.",
    "dialog.remeber_number": "تذكر الرقم الموجود على هذا الكمبيوتر",
    "dialog.removed_by_host": "تمت إزالتك من هذا المؤتمر من قبل المضيف.",
    "dialog.something_wrong": "هناك خطأ ما",
    "dialog.toll": "رسوم",
    "dialog.tollfree": "اتصال مجاني",
    "dialog.warning": "لا تحذرني مرة أخرى.",
    "disclaimer.poll_button_1": "من يمكنه رؤية ردودك؟",
    "disclaimer.poll_content_bAnonymous": "هذا استطلاع مجهول الهوية ، لذا لن يتمكن مالك الحساب والمضيف من معرفة من أرسل هذه الردود.",
    "disclaimer.poll_content_noAnonymous": "سيتمكن مالك الحساب والمضيف من معرفة هويتك ومعلومات الاتصال الخاصة بك (إذا قمت بتسجيل الدخول أو قدمتها) وردودك - ويمكنهما مشاركتها مع التطبيقات وغيرها.",
    "donnot_allow_to_multi_pin": "لا تسمح لـ Multi-pin",
    "dont_support": "لا تدعم",
    "edit": "يحرر",
    "find_join_link": "لا يمكن العثور على رابط الانضمام الخاص بك؟",
    "general": "عام",
    "get_join_tk": "أين يمكنني الحصول على رابط الانضمام؟",
    "has_been_removed_dialog.ok_text": "يترك",
    "helper.confirm_desc": "انقر فوق \"{0}\" للمتابعة. يرجى البقاء على هذه الصفحة قبل إتمام العملية.",
    "helper.confirm_title": "تأكيد {0}",
    "interpretation": "تفسير",
    "interpretation.available_tip1": "{0} و {1} الترجمة الفورية متاحة",
    "interpretation.available_tip2": "{0} و {1} تفسيرات لغوية أخرى متوفرة",
    "interpretation.cn": "صينى",
    "interpretation.de": "ألمانية",
    "interpretation.en": "إنجليزي",
    "interpretation.end_tip": "تم إنهاء الترجمة اللغوية من قبل المضيف",
    "interpretation.es": "الأسبانية",
    "interpretation.fr": "فرنسي",
    "interpretation.jp": "اليابانية",
    "interpretation.kr": "الكورية",
    "interpretation.mute_original_audio": "كتم الصوت الأصلي",
    "interpretation.original_audio": "الصوت الأصلي",
    "interpretation.pt": "البرتغالية",
    "interpretation.ru": "الروسية",
    "interpretation.unmute_original_audio": "إعادة الصوت الأصلي",
    "interpreter": "مترجم",
    "invite.and": "و",
    "invite.others": "آحرون",
    "ip_address": "عنوان IP:",
    "join_3prty_audio": "انضم عن طريق صوت طرف ثالث",
    "link_or_tk": "رابط الانضمام أو TK",
    "login_register_text": "لا يوجد حساب Zoom؟",
    "logout": "تسجيل خروج",
    "meeting": "مقابلة",
    "meeting_accept": "تم قبول المكالمة",
    "meeting_busy": "مشغول",
    "meeting_calling": "الاتصال",
    "meeting_disconnect": "قطع الاتصال",
    "meeting_fail": "فشل في الاتصال",
    "meeting_fail_disconnect": "فشل في قطع الاتصال",
    "meeting_hide_non_video": "إخفاء غير المشاركين في الفيديو",
    "meeting_hide_self_view": "إخفاء العرض الذاتي",
    "meeting_id": "معرف المؤتمر: {0}",
    "meeting_is_host": "أنت مضيف الآن.",
    "meeting_recording": "تسجيل...",
    "meeting_ringing": "رنين...",
    "meeting_success": "نجاح",
    "meeting_unlock_to_invite": "تم قفل المؤتمر ، يرجى فتح القفل أولاً للدعوة.",
    "merge_audio_video": "دمج {0} مع الفيديو",
    "merge_video_audio": "دمج الفيديو الخاص بـ {0} مع الصوت",
    "no": "لا",
    "polling.AddA_Poll": "أضف استطلاع",
    "polling.AllowPanelistToVote": "السماح لأعضاء اللجنة بالتصويت",
    "polling.AttendeesAreNowViewingPollResults": "الحاضرون يشاهدون الآن نتائج الاستطلاع",
    "polling.ClockAriaLabelShort": "لقد استمرت {0} دقيقة و {1} ثانية.",
    "polling.Close": "يغلق",
    "polling.Conflict": "لقد قمت بتسجيل الدخول من جهاز آخر. جلسة الاقتراع الخاصة بك غير نشطة.",
    "polling.Correct": "صحيح!",
    "polling.CorrectAnswer": "الإجابة الصحيحة: {0}",
    "polling.CorrectAnswerIs": "الإجابة الصحيحة هي",
    "polling.Create": "يخلق",
    "polling.DisplayQuestionsInARandomOrder": "اعرض الأسئلة بترتيب عشوائي",
    "polling.Download": "تحميل",
    "polling.DownloadResults": "تحميل النتائج",
    "polling.EditPoll": "تحرير الاستطلاع",
    "polling.EndPoll": "إنهاء الاستطلاع",
    "polling.FillInTheBlank": "(املاء الفراغ)",
    "polling.HostAndParticipantsCantVote": "لا يمكن للمضيف والمشاركين التصويت",
    "polling.HostIsSharingPullResults": "المضيف يشارك نتائج الاستطلاع",
    "polling.Launch": "يطلق",
    "polling.Launching": "إطلاق...",
    "polling.LongAnswer": "(اجابة طويلة)",
    "polling.Matching": "(مطابقة)",
    "polling.MultipleChoice": "(متعدد الخيارات)",
    "polling.Next": "التالي",
    "polling.NoPollsOrQuizzesCreated": "لم يتم إنشاء استطلاعات الرأي أو الاختبارات القصيرة",
    "polling.NumberOfNumberAnswered": "تمت الإجابة على {0} من {1}",
    "polling.NumberOfNumberPercentAnswered": "أجاب {0}",
    "polling.PleaseEnterAnAnswer": "الرجاء إدخال إجابة",
    "polling.PleaseEnterAtLeastCharacters": "الرجاء إدخال {0} حرف على الأقل",
    "polling.PleaseSelectAnAnswer": "الرجاء تحديد إجابة",
    "polling.PollEnded": "انتهى الاستطلاع",
    "polling.PollFillItemTitleAriaLabel": "السؤال له {0} إجابة بديلة.",
    "polling.PollResult": "نتيجة الاستطلاع",
    "polling.PollingClosed": "التصويت مغلق",
    "polling.PollingComputedSummaryData": "صوت {0} من {1} ({2})",
    "polling.PollingIndex": "استطلاع رقم {0}:",
    "polling.Polls": "تصويت",
    "polling.Preview": "معاينة",
    "polling.Previous": "سابق",
    "polling.Questions": "أسئلة",
    "polling.Quiz": "اختبار",
    "polling.QuizEnded": "انتهى الاختبار",
    "polling.RankOrder": "(ترتيب الترتيب)",
    "polling.RatingScale": "(مقياس التصنيف)",
    "polling.ReLaunch": "إعادة الإطلاق",
    "polling.ReLaunchPoll": "إعادة إطلاق الاستطلاع",
    "polling.Relaunching": "جارٍ إعادة الإطلاق ...",
    "polling.Retry": "أعد المحاولة",
    "polling.ReviewResult": "نتيجة المراجعة",
    "polling.SelectAnswer": "حدد إجابة",
    "polling.ShareResult": "نتيجة المشاركة",
    "polling.Sharing": "مشاركة...",
    "polling.SharingPollResults": "مشاركة نتائج الاستطلاع",
    "polling.ShortAnswer": "(اجابة قصيرة)",
    "polling.ShowCorrectAnswersToAll": "أظهر الإجابات الصحيحة للجميع",
    "polling.ShowOneQuestionAtATime": "عرض سؤال واحد في كل مرة",
    "polling.SingleChoice": "(خيار واحد)",
    "polling.StopSharing": "التوقف عن المشاركة",
    "polling.Submit": "يُقدِّم",
    "polling.TheCorrectAnswerIs": "والجواب الصحيح هو:",
    "polling.TheCorrectAnswersAre": "الجواب الصحيح:",
    "polling.ViewDetails": "عرض التفاصيل",
    "polling.ViewResultsFromBroswer": "عرض النتائج من المستعرض",
    "polling.YouAreViewingThePollResultsSharedByHost": "أنت تشاهد نتائج الاستطلاع (مشتركة بواسطة المضيف)",
    "polling.YouAreViewingYourQuizResults": "أنت تشاهد نتائج الاختبار الخاص بك",
    "polling.YourAnswer": "إجابتك: {0}",
    "polling.clear_warn": "ستؤدي إعادة إطلاق الاستطلاع إلى مسح نتائج الاقتراع الحالية. هل تريد الاستمرار؟",
    "polls": "استطلاعات الرأي",
    "promote.content_2": "إذا قرر المضيف أو أعضاء اللجنة الآخرون تسجيل الندوة عبر الويب أو بثها المباشر أو أرشفتها بعد إلغاء كتم الصوت ، فسيتم تضمين مشاركتك.",
    "reaction.category_label_activity": "نشاط",
    "reaction.category_label_flags": "أعلام",
    "reaction.category_label_food": "طعام شراب",
    "reaction.category_label_nature": "الحيوانات والطبيعة",
    "reaction.category_label_objects": "أشياء",
    "reaction.category_label_people": "الوجوه الضاحكة والأشخاص",
    "reaction.category_label_symbols": "حرف او رمز",
    "reaction.category_label_travel": "السفر والأماكن",
    "reaction.download_progress": "تنزيل الرموز التعبيرية ({0}٪)",
    "reaction.emojis_download_failed": "لا يمكن تنزيل مكتبة الرموز التعبيرية",
    "reaction.frequently_used": "كثيرا ما تستخدم",
    "reaction.processing_emojis": "معالجة الرموز التعبيرية",
    "reaction.search": "يبحث",
    "reaction.search_results": "نتائج البحث",
    "reaction.skin_tone": "لون البشرة:",
    "real_name_verification": "التحقق من الاسم الحقيقي",
    "recaptcha": "ريكابتشا",
    "recorded": "مسجل",
    "redirect_text": "إعادة التوجيه في 3 ثوان ...",
    "register": "يسجل",
    "registering": "التسجيل",
    "registration": "تسجيل",
    "registration_auto_desc": "يرجى التحقق من البريد الإلكتروني للتأكيد المرسل إلى {0}.",
    "registration_auto_header": "لقد قمت بالتسجيل بنجاح",
    "registration_manual_approved": "تم الموافقة على تسجيلك",
    "registration_manual_desc": "بعد أن يقوم المضيف بمراجعة تفاصيل التسجيل الخاصة بك ، ستتلقى رسالة بريد إلكتروني حول حالة التسجيل الخاصة بك.",
    "registration_manual_header": "التسجيل الخاص بك في انتظار الموافقة",
    "registration_meeting": "اجتماع التسجيل",
    "registration_webinar": "ندوة التسجيل عبر الويب",
    "rmc.click_to_copied": "انقر للنسخ",
    "rmc.copy": "ينسخ",
    "rmc.main_description_text": "لا يمكن لأي مشاركين في الاجتماع رؤيتك في هذا الاجتماع باستثناء المضيف.",
    "rmc.main_header_text": "أنت في وضع التحكم في الاجتماع",
    "rmc.topic": "عنوان",
    "security.remove_participant": "إزالة المشارك",
    "security.rename_themselves": "إعادة تسمية أنفسهم",
    "security.report": "تقرير",
    "security.report_display_user_avatars": "عرض صور الملف الشخصي",
    "security.report_hide_user_avatars": "إخفاء صور الملف الشخصي",
    "security.report_suspend_activities_title": "تعليق جميع أنشطة المشاركين؟",
    "security.report_suspend_btn": "تعليق",
    "security.report_suspend_dialog_content": "سيتم إيقاف تشغيل الفيديو والصوت لدى الجميع ، وستتوقف مشاركة الشاشة ، وسيتم قفل الاجتماع.",
    "security.report_suspend_user_activities": "تعليق أنشطة المشاركين",
    "security.report_to_zoom": "تقرير للتكبير",
    "security.unmute_themselves": "أبكموا أنفسهم",
    "security.upload_file": "رفع ملف",
    "security.waiting_room_notification_1": "لقد قمت بتمكين غرفة الانتظار",
    "security.waiting_room_notification_2": "لقد قمت بتعطيل غرفة الانتظار",
    "see_waiting_room": "انظر غرفة الانتظار",
    "settings.disable_hd": "",
    "settings.disable_hd_tip": "",
    "settings.download_failed_image": "تعذر تنزيل الخلفية",
    "settings.mask_loading_error1": "غير قادر على بدء الفيديو في هذا الوقت.",
    "settings.mask_loading_error2": "الرجاء حل الخطأ و <a> إعادة تشغيل الفيديو. </a>",
    "settings.reaction_skin_tone": "رد فعل لون الجلد",
    "sign_in": "تسجيل الدخول",
    "sign_up_free": "الاشتراك مجانا",
    "signing_in": "تسجيل الدخول",
    "sms_verification": "التحقق من الرسائل القصيرة",
    "start_time": "وقت البدء",
    "title_join_meeting": "انضمام",
    "toolbar_ask_all_unmute": "اطلب من الجميع إلغاء كتم الصوت",
    "toolbar_invite": "يدعو",
    "toolbar_lock": "قفل",
    "toolbar_unlock": "الغاء القفل",
    "toolbar_unmuteall": "إعادة صوت الكل",
    "turn_off_watermark_text": "إعدادات التسمية التوضيحية",
    "turn_on_watermark_text": "قم بتشغيل العلامة المائية",
    "update_firefox": "يُرجى ترقية إصدار Firefox لديك إلى 76.0 أو أعلى.",
    "valid_token": "يرجى تقديم معارف تقليدية صالحة",
    "verify_email": "التحقق من البريد الإلكتروني",
    "video.follow_host_video_order": "اتبع طلب الفيديو الخاص بالمضيف",
    "video.release_video_order": "الافراج عن طلب الفيديو",
    "video_cannot_move_video": "لا يمكن نقل الفيديو",
    "video_cannot_move_video_follow_host_order": "لا يمكنك نقل مقطع فيديو لأنك تتبع ترتيب الفيديو الخاص بالمضيف",
    "video_cannot_move_video_has_pin": "لا يمكنك نقل مقطع فيديو أثناء تثبيت الأشخاص",
    "video_cannot_move_video_has_raise_hand": "لا يمكنك تحريك مقطع فيديو بينما يرفع شخص ما يده",
    "video_cannot_move_video_has_spotlight": "لا يمكنك نقل مقطع فيديو أثناء تسليط الضوء على الأشخاص",
    "video_cannot_move_video_hide_non_video": "لا يمكنك نقل مقطع فيديو أثناء إخفاء المشاركين الذين ليسوا في الفيديو",
    "video_cannot_move_video_hide_self_video": "لا يمكنك نقل مقطع فيديو أثناء إخفاء الفيديو الخاص بك",
    "waiting": "منتظر...",
    "waiting_room.host_lost": "الرجاء الانتظار ، فقد المضيف الاتصال",
    "waiting_verify_tk": "انتظر للتحقق مما إذا كان الاجتماع / الندوة عبر الويب قد بدأ وتحقق من المعارف التقليدية",
    "wc_3rd_cc_url_copied": "تم نسخ URL إلى الحافظة الخاصة بك",
    "wc_3rd_cc_url_copy_to_clipboard": "انسخ عنوان URL إلى الحافظة الخاصة بك",
    "wc_3rd_cc_url_help_tips": "انسخ هذا الرابط والصقه في الجزء الثالث CC typer",
    "wc_admit_to_main_session": "اعترف بالجلسة الرئيسية",
    "wc_all_participants": "جميع المشاركين",
    "wc_allow_attendees_to_raise_hand": "السماح للحاضرين برفع اليد",
    "wc_allow_chime_enter_exit": "تشغيل الرنين للدخول / الخروج",
    "wc_allow_raise_hand": "اسمح للمشاركين برفع اليد",
    "wc_allow_rename": "اسمح للمشاركين بإعادة تسمية أنفسهم",
    "wc_allow_to_talk_disabled": "السماح بالتحدث غير متاح لأن {0} يستخدم إصدارًا أقدم من Zoom. اختر Promote Panelist للسماح لـ {1} بالتحدث.",
    "wc_allow_unmute": "اسمح للمشاركين بإعادة صوت أنفسهم",
    "wc_already_joined_by_telephone": "انضم بالفعل عن طريق الهاتف؟ يضعط #",
    "wc_aria_sharer_setting_menu_entry_button_text": "إعداد إذن المشاركة",
    "wc_aria_txt_dialog_close_btn": "يغلق",
    "wc_assign_cc_confirm": "تم تعيين {0} حاليًا لكتابة تسمية توضيحية مغلقة ، هل تريد تعيين {1} للكتابة بدلاً من ذلك؟",
    "wc_audio.unmute_by_host_content_2": "إذا اخترت إلغاء كتم الصوت ، فسيتمكن الآخرون في الندوة من سماعك. إذا قرر المضيف أو أعضاء اللجنة تسجيل الندوة عبر الويب أو بثها المباشر أو أرشفتها بعد إلغاء كتم الصوت ، فسيتم تضمين صوتك.",
    "wc_audio.unmuted_notification1": "المضيف يعيد كتم صوتك",
    "wc_audio.using_audio_dial_tip": "تم توصيل الصوت الخاص بك باستخدام Dial In",
    "wc_audio.using_audio_tip": "الصوت الخاص بك متصل باستخدام صوت الكمبيوتر",
    "wc_audio_options": "خيارات الصوت",
    "wc_auto_join_audio": "ضم الصوت تلقائيًا عن طريق الكمبيوتر عند الانضمام إلى مؤتمر",
    "wc_beackout_room_participants": "المشاركون في غرفة الاستراحة",
    "wc_bo.all_room_will_close": "سيتم إغلاق جميع الغرف الفرعية في غضون {0} ثانية.",
    "wc_bo.ask_for_help": "طلب المساعدة",
    "wc_bo.ask_for_help_content": "يمكنك دعوة المضيف إلى غرفة الاستراحة هذه للحصول على المساعدة",
    "wc_bo.ask_host_for_help_tip": "طلب {0} في {1} المساعدة.",
    "wc_bo.assign_rooms": "قم بتعيين {0} مشاركين في {1} الغرف.",
    "wc_bo.assign_rooms_2": "أنشئ {0} غرفة جانبية",
    "wc_bo.assign_rooms_3": "أعد إنشاء {0} غرفة فرعية",
    "wc_bo.be_assigned_to_room_tip": "لقد تم تخصيصك لغرفة الاستراحة",
    "wc_bo.broadcast_message_to_all": "بث رسالة للجميع",
    "wc_bo.broadcast_tips": "سيتم إرسال البث إلى الجميع.",
    "wc_bo.choose_breakout_room": "اختر غرفة الاستراحة",
    "wc_bo.choose_room_tip": "اختر غرفة استراحة مختلفة",
    "wc_bo.close_breakout_room": "أغلق غرفة الاستراحة",
    "wc_bo.close_now": "إغلاق الآن",
    "wc_bo.close_room_tip_when_time_up": "انتهى وقت غرفة الاجتماعات الفرعية التي تبلغ مدتها {0} دقيقة. هل تريد إغلاق جميع الغرف الفرعية الآن؟",
    "wc_bo.current_room_will_close": "سيتم إغلاق الغرف الفرعية في غضون {0} ثانية.",
    "wc_bo.default_room_name": "الإستراحة",
    "wc_bo.default_room_name2": "غرفة",
    "wc_bo.delete_room_confirm_tip": "حذف {0}؟",
    "wc_bo.distrubution": "توزيع",
    "wc_bo.distrubution_auto": "تلقائيا",
    "wc_bo.distrubution_manually": "يدويا",
    "wc_bo.distrubution_self_select": "اسمح للمشاركين باختيار الغرفة",
    "wc_bo.exchange": "تبادل",
    "wc_bo.host_in_bo_waitingroom_tip": "لقد انضم {0} من الأشخاص إلى غرفة الانتظار لهذا الاجتماع. يمكنك العودة إلى الجلسة الرئيسية للمسؤول.",
    "wc_bo.host_join_bo_tip": "أنت الآن في غرفة الاستراحة",
    "wc_bo.host_leave_meeting_in_bo": "استمر في تشغيل الاجتماع للآخرين",
    "wc_bo.host_move_you": "قام المضيف بنقلك إلى",
    "wc_bo.invite_host": "دعوة المضيف",
    "wc_bo.invite_host_failed_tip": "المضيف حاليا يساعد الآخرين. الرجاء معاودة المحاولة في وقت لاحق.",
    "wc_bo.invite_host_success_tip": "تمت دعوة المضيف.",
    "wc_bo.invite_host_success_tip2": "المضيف حاليا في هذه الغرفة.",
    "wc_bo.invite_join_room_tip_content": "يدعوك المضيف للانضمام إلى غرفة الاستراحة:",
    "wc_bo.invite_join_room_tip_default_host": "المضيف",
    "wc_bo.join": "انضمام",
    "wc_bo.join_a_room": "انضم إلى غرفة الاستراحة",
    "wc_bo.join_room__confirm_tip": "الانضمام إلى {0}؟",
    "wc_bo.join_room_tip_content": "تم تعيينك في غرفة الاستراحة:",
    "wc_bo.joining_rooms": "الانضمام إلى غرف الاجتماعات ...",
    "wc_bo.joining_rooms2": "الانضمام إلى {0} ...",
    "wc_bo.keep_bo_open": "حافظ على غرف الاستراحة مفتوحة",
    "wc_bo.later": "لاحقاً",
    "wc_bo.leave": "يترك",
    "wc_bo.leave_room_confirm_tip": "مغادرة {0}؟",
    "wc_bo.leave_room_tips": "هل تريد مغادرة الغرفة الفرعية والعودة إلى الجلسة الرئيسية؟",
    "wc_bo.leave_room_tips2": "هل تريد مغادرة غرفة الاحتراق هذه؟ إذا غادرت ، لا يمكنك العودة إلى الاجتماع الرئيسي.",
    "wc_bo.loading": "جارٍ تحميل الغرف ...",
    "wc_bo.moving_into_rooms": "قام المضيف بنقلك إلى",
    "wc_bo.options": "خيارات",
    "wc_bo.options_allow_participants_choose_room": "اسمح للمشاركين باختيار الغرفة",
    "wc_bo.options_countdowntime2": "ضبط العد التنازلي",
    "wc_bo.options_countdowntime3": "{0} ثانية",
    "wc_bo.perroom_size": "{0} مشارك لكل غرفة",
    "wc_bo.please_input": "الرجاء الإدخال",
    "wc_bo.recover_confirm_tip": "هل تريد العودة إلى الغرف المعينة مسبقًا؟ سيتم استبدال جميع الغرف الموجودة.",
    "wc_bo.recover_preassign": "استعد إلى الغرف المخصصة مسبقًا",
    "wc_bo.recreate_all_rooms": "أعد إنشاء جميع الغرف",
    "wc_bo.recreate_tips": "سيتم استبدال جميع الغرف الموجودة.",
    "wc_bo.remaining": "متبقي:",
    "wc_bo.return_main_session_tip": "أنت الآن في الجلسة الرئيسية",
    "wc_bo.return_to_main_session_dialog": "يدعوك {0} للعودة إلى الجلسة الرئيسية.",
    "wc_bo.returning_to_main_session": "العودة إلى الجلسة الرئيسية ...",
    "wc_bo.room_has_started_notify": "افتتح المضيف Breakout Rooms. يرجى الانتظار حتى يتم تخصيصها.",
    "wc_bo.take_few_moments": "قد يستغرق الأمر بضع لحظات.",
    "wc_bo.where_join_room_tip": "يمكنك الانضمام إلى Breakout Rooms من هنا.",
    "wc_bo_disallow_mic": "المتصفح يمنع الميكروفون",
    "wc_brand": "تكبير",
    "wc_browser_not_support": "متصفحك غير مدعوم",
    "wc_browser_not_support2": "يرجى تجربة أحد هذه الخيارات لتحسين تجربتك وأمنك.",
    "wc_busy": "مشغول",
    "wc_call": "يتصل",
    "wc_call_a_H323": "اتصل بنظام غرفة H.323 / SIP",
    "wc_call_out": "صرخ",
    "wc_change_browser": "متصفحك لا يدعم استخدام جهاز الصوت بالكمبيوتر. لاستخدام Zoom ، قم بتثبيت أحدث إصدار من متصفح قياسي ، مثل Chrome أو Firefox.",
    "wc_chat.all_panelists": "كل أعضاء اللجنة",
    "wc_chat.allow_chat_with": "السماح للحاضرين بالدردشة مع",
    "wc_chat.cc_panelists": "وجميع أعضاء اللجنة.",
    "wc_chat.close": "يغلق",
    "wc_chat.disable_chat": "قام المضيف بتعطيل محادثة الحضور.",
    "wc_chat.everyone_public": "الجميع علنًا",
    "wc_chat.everyone_public_private": "الجميع في السر والعلن",
    "wc_chat.expand": "يوسع",
    "wc_chat.from": "من",
    "wc_chat.group_chat": "Zoom دردشة جماعية",
    "wc_chat.host_only": "المضيف فقط",
    "wc_chat.improper_receiver": "لا يمكنك الدردشة مع {0} أثناء هذا الاجتماع",
    "wc_chat.in_meeting": "في الاجتماع",
    "wc_chat.in_waiting_room": "في غرفة الانتظار",
    "wc_chat.meeting_message": "رسائل الاجتماع",
    "wc_chat.merge_to_window": "دمج في نافذة الاجتماع",
    "wc_chat.minimize": "تصغير",
    "wc_chat.new_msg": "رسالة جديدة",
    "wc_chat.no_one": "لا احد",
    "wc_chat.not_in_meeting": "ليس في هذا الاجتماع",
    "wc_chat.panelists_attendees": "جميع أعضاء اللجنة والحضور",
    "wc_chat.popout": "يقتلع",
    "wc_chat.privately": "(بشكل خاص)",
    "wc_chat.to": "ل",
    "wc_chat.uppercase_to": "ل",
    "wc_chat.waiting_room_warning": "يمكن للمضيف والمضيف المشارك فقط إرسال رسائل إلى كل شخص في غرفة الانتظار",
    "wc_choose_email_service": "اختر خدمة البريد الإلكتروني لإرسال دعوة",
    "wc_closed_caption_available": "التسمية التوضيحية المغلقة متاحة",
    "wc_closed_caption_truned_on": "تم تشغيل \"التسمية التوضيحية المغلقة\"",
    "wc_cloud_recording": "التسجيل السحابي",
    "wc_co_host_me": "(مضيف مشارك ، أنا)",
    "wc_copy_invitation": "نسخ الدعوة",
    "wc_copy_url": "إنسخ الرابط",
    "wc_data_center1": "أنت متصل بشبكة Zoom العالمية عبر مركز بيانات في {0}.",
    "wc_data_center4": "أنت متصل بـ {0} عبر مركز بيانات في {1}.",
    "wc_decline": "انخفاض",
    "wc_default_email": "البريد الإلكتروني الافتراضي",
    "wc_device_not_support_desc": "إذا كنت ترغب في استخدام هذه الميزة ، يرجى استخدام Chrome أو Firefox للانضمام إلى هذا الاجتماع مرة أخرى.",
    "wc_device_not_support_title": "متصفحك لا يدعم ميزة - مشاركة الشاشة",
    "wc_dial": "يتصل",
    "wc_dial_in": "يتصل ب",
    "wc_dial_in_H323": "اطلب من نظام غرفة H.323 / SIP",
    "wc_disconnected": "انقطع الاتصال",
    "wc_do_not_show_again": "لا تظهر هذا مرة أخرى",
    "wc_e2e_encryption": "التشفير من طرف إلى طرف",
    "wc_email": "بريد إلكتروني",
    "wc_encrypted": "اتصال العميل الخاص بك مشفر",
    "wc_end": "إنهاء",
    "wc_enhanced_encryption": "تشفير محسن",
    "wc_enter_meeting_id": "أدخل معرف الاجتماع",
    "wc_enter_pairing_code": "أدخل رمز الاقتران",
    "wc_enter_password": "الرجاء إدخال رمز مرور صالح",
    "wc_extra_function_start_incoming_video": "بدء الفيديو الوارد",
    "wc_extra_function_stop_incoming_video": "وقف الفيديو الوارد",
    "wc_failed": "فشل",
    "wc_feature_tip": "{0} و {1} متاحان",
    "wc_find_a_participant": "ابحث عن مشارك",
    "wc_focus_mode": "وضع التركيز",
    "wc_focus_mode_dialog_content": "سيتمكن المشاركون فقط من رؤية مقاطع الفيديو الخاصة بالمضيفين والمحتوى المشترك ومقاطع الفيديو الخاصة بالمشاركين البارزين.",
    "wc_focus_mode_dialog_content_note": "ملاحظة: يمكنك السماح بعرض المحتوى المشترك للجميع في قائمة \"مشاركة الشاشة\".",
    "wc_focus_mode_dialog_silence": "لا تسألني مرة أخرى",
    "wc_focus_mode_ending": "وضع التركيز على وشك الانتهاء. سيشاهد الجميع المشاركين الذين بدأوا الفيديو.",
    "wc_focus_mode_hosts_tips": "هذا الاجتماع في وضع التركيز. يمكن للمشاركين مشاهدة مقاطع الفيديو الخاصة بالمضيفين والمحتوى المشترك ومقاطع الفيديو الخاصة بالمشاركين المميزين فقط.",
    "wc_focus_mode_others_tips": "هذا الاجتماع في وضع التركيز. يمكنك فقط مشاهدة مقاطع الفيديو الخاصة بالمضيفين والمشاركين المميزين ، بالإضافة إلى المحتوى المشترك من قبل الجميع.",
    "wc_focus_mode_share": "يمكن رؤية الشاشات المشتركة بواسطة",
    "wc_focus_mode_share_toast_hosts": "يكون المحتوى الذي يشاركه المشاركون مرئيًا فقط للمضيفين والمشاركين في الاستضافة",
    "wc_focus_mode_spotlighted": "يمكن للجميع مشاهدة الفيديو الخاص بك لأن المضيف سلط الضوء عليك",
    "wc_focus_mode_toast_for_ptcp": "الاجتماع في وضع التركيز: يمكن للمضيف والمضيفين المشاركين فقط مشاهدة الفيديو الخاص بك.",
    "wc_focus_mode_toast_forhost": "يمكن للمشاركين رؤية المضيف والمضيفين المشاركين والمستخدمين البارزين فقط",
    "wc_focus_mode_toast_share_all": "يمكن لجميع المشاركين رؤية شاشتك المشتركة",
    "wc_focus_mode_toast_share_hostonly": "لا يمكن رؤية شاشتك المشتركة إلا من قبل المضيف والمضيفين المشاركين",
    "wc_follow_intro_join_audio": "اتبع التعليمات أدناه للانضمام إلى الصوت",
    "wc_footer_keep_phone_connected": "حافظ على اتصال الهاتف",
    "wc_gmail": "بريد جوجل",
    "wc_h323": "H.323",
    "wc_help": "يساعد",
    "wc_host": "(يستضيف)",
    "wc_hostme": "(تستضيف لي)",
    "wc_how_to_allow": "كيفية السماح بالوصول إلى الميكروفون الخاص بك.",
    "wc_invitation_url": "عنوان URL للدعوة",
    "wc_invite_by_email": "ادعو بواسطة البريد الإلكتروني",
    "wc_invite_by_phone": "دعوة عن طريق الهاتف",
    "wc_invite_email_subject": "يرجى الانضمام إلى اجتماع {0} قيد التقدم",
    "wc_invite_title": "دعوة الناس للانضمام إلى الاجتماع",
    "wc_invitee_name": "اسم المدعو",
    "wc_is_sharing_desktop": "يقوم بمشاركة سطح المكتب",
    "wc_join": "انضمام",
    "wc_join_audio_by_pc": "انضم إلى الصوت عن طريق الكمبيوتر",
    "wc_join_audio_timeout": "Zoom غير قادر مؤقتًا على استخدام أجهزة الكمبيوتر للاتصال بصوت الاجتماع. انقر فوق \"الانضمام إلى الصوت عن طريق الكمبيوتر\" للمحاولة مرة أخرى.",
    "wc_join_media_preview_info_tooltip": "سيتم استخدام تفضيلات الصوت والفيديو التي تحددها هنا للاجتماعات المستقبلية.",
    "wc_join_media_preview_warning_not_found_both": "تعذر اكتشاف الكاميرا أو الميكروفون. يرجى التحقق من جهازك وحاول مرة أخرى.",
    "wc_join_media_preview_warning_not_found_camera": "تعذر اكتشاف الكاميرا. يرجى التحقق من جهازك وحاول مرة أخرى.",
    "wc_join_media_preview_warning_not_found_mic": "تعذر اكتشاف ميكروفون. يرجى التحقق من جهازك وحاول مرة أخرى.",
    "wc_join_media_preview_warning_occupied_both": "تستخدم تطبيقات أخرى الكاميرا والميكروفون. الرجاء إغلاق التطبيقات وحاول مرة أخرى.",
    "wc_join_media_preview_warning_occupied_camera": "يتم استخدام الكاميرا الخاصة بك بواسطة تطبيقات أخرى. الرجاء إغلاق التطبيقات وحاول مرة أخرى.",
    "wc_join_media_preview_warning_occupied_mic": "يتم استخدام الميكروفون الخاص بك من قبل تطبيقات أخرى. الرجاء إغلاق التطبيقات وحاول مرة أخرى.",
    "wc_join_media_preview_warning_unknown_both": "الصوت والفيديو غير متاحين للاستخدام في الوقت الحالي. حاول مرة اخرى.",
    "wc_join_media_preview_warning_unknown_camera": "الفيديو غير متاح للاستخدام في هذا الوقت. حاول مرة اخرى.",
    "wc_join_media_preview_warning_unknown_mic": "الصوت غير متاح للاستخدام في الوقت الحالي. حاول مرة اخرى.",
    "wc_join_not_support_e2ee_meeting": "الاجتماعات المشفرة من طرف إلى طرف غير مدعومة على المتصفح في الوقت الحالي",
    "wc_learn": "يتعلم",
    "wc_leave_page_feedback_back": "خلف",
    "wc_leave_pc_audio": "اترك صوت الكمبيوتر",
    "wc_leave_room": "غادر الغرفة",
    "wc_login_timeout": "نفذ الوقت",
    "wc_lt_available": "النسخ المباشر متاح",
    "wc_lt_close": "يغلق",
    "wc_lt_popout": "يقتلع",
    "wc_lt_truned_of": "تم إيقاف \"النسخ المباشر\"",
    "wc_lt_truned_on": "تم تشغيل \"النسخ المباشر\"",
    "wc_make_co_host_text": "هل تريد أن تجعل {0} المضيف المشارك لهذا الاجتماع؟",
    "wc_make_host_text": "هل تريد تغيير المضيف إلى",
    "wc_mask_feature_tips": "اخفاء خلفيتك",
    "wc_meeting.lock_notification": "لقد أغلقت الاجتماع. لا أحد يستطيع الانضمام.",
    "wc_meeting.unlock_notification": "لقد ألغيت قفل الاجتماع. يمكن للمشاركين الجدد الانضمام.",
    "wc_meeting_timeout": "انتهت مهلة اتصالك ولا يمكنك الانضمام إلى الاجتماع. تحقق من اتصال الشبكة وحاول مرة أخرى.",
    "wc_meeting_timeout_title": "انتهت مهلة الانضمام إلى الاجتماع.",
    "wc_merge_audio_1": "دمج مع الصوت ...",
    "wc_merge_audio_2": "دمج مع الفيديو ...",
    "wc_message": "رسالة",
    "wc_mute_participants_on_entry": "كتم صوت المشاركين عند الدخول",
    "wc_muteall_desc": "سيتم كتم صوت المشاركين الحاليين والجدد",
    "wc_new": "جديد",
    "wc_nonverbal.away": "بعيد",
    "wc_nonverbal.break": "بحاجة إلى استراحة",
    "wc_nonverbal.clap": "صفق",
    "wc_nonverbal.clear_all": "امسح الكل",
    "wc_nonverbal.dislike": "لم يعجبنى",
    "wc_nonverbal.go_faster": "اسرع",
    "wc_nonverbal.go_slower": "الذهاب أبطأ",
    "wc_nonverbal.like": "يحب",
    "wc_nonverbal.lower_hand": "اليد السفلى",
    "wc_nonverbal.more": "أكثر",
    "wc_nonverbal.no": "لا",
    "wc_nonverbal.raise_hand": "رفع اليد",
    "wc_nonverbal.yes": "نعم",
    "wc_on_your_phone": "على هاتفك",
    "wc_other_is_host": "هو المضيف الآن.",
    "wc_participants_title1": "مشارك في الاجتماع",
    "wc_participants_title2": "المشاركين في الاجتماع",
    "wc_pc_audio_connected": "صوت الكمبيوتر - متصل",
    "wc_phone": "هاتف",
    "wc_phone_call": "مكالمة هاتفية",
    "wc_phone_call_connected": "مكالمة هاتفية - متصلة",
    "wc_phone_connected": "الهاتف متصل",
    "wc_play_chime_notification": "قم بتشغيل الرنين للدردشة ورفع الإخطار اليدوي",
    "wc_pure_audio_meeting": "اجتماع صوتي نقي",
    "wc_put_in_waiting_entry": "ضع الحاضر في غرفة الانتظار عند الدخول",
    "wc_put_on_hold_msg": "يُرجى الانتظار ، سيسمح لك مضيف الاجتماع بالدخول قريبًا.",
    "wc_qa.cancel": "يلغي",
    "wc_qa.pending_questions_tips": "أسئلة مفتوحة",
    "wc_qa.qa_comp_ally_title": "سؤال وجواب",
    "wc_quality": "جودة",
    "wc_record_reminder_desc_1": "من خلال البقاء في هذا الاجتماع ، فإنك توافق على التسجيل.",
    "wc_recording_pause_stop": "وقفة / إيقاف التسجيل",
    "wc_recording_paused": "توقف التسجيل مؤقتًا",
    "wc_recording_resume_stop": "استئناف / إيقاف التسجيل",
    "wc_remote_control.can_control": "يمكنك التحكم في شاشة {0}",
    "wc_remote_control.give_up": "التخلي عن جهاز التحكم عن بعد",
    "wc_remote_control.is_controlling": "أنت تتحكم في شاشة {0}",
    "wc_remote_control.request": "طلب جهاز تحكم عن بعد",
    "wc_remote_control.text1": "أنت على وشك طلب التحكم عن بعد في محتوى {0} المشترك.",
    "wc_remote_control.text2": "حدد [طلب] وانتظر موافقة {0}.",
    "wc_remote_control.text3": "حدد [إلغاء] إذا كنت لا تريد إرسال طلب.",
    "wc_remote_control.text4": "{0} رفض طلبك.",
    "wc_remote_control.text5": "حدد [طلب] للمحاولة مرة أخرى.",
    "wc_remove_all_pin_title": "قم بإزالة جميع مقاطع الفيديو المثبتة",
    "wc_remove_user": "هل تريد إزالة",
    "wc_removed_tip": "تمت إزالة {0}",
    "wc_ring": "جرس",
    "wc_room_system": "نظام الغرفة",
    "wc_security.report_additional_comments": "تعليقات اضافية",
    "wc_security.report_all_privacy_policy": "بإرسال هذا التقرير ، فإنك تفوض Zoom للوصول إلى جميع البيانات الواردة في هذا التقرير ، والتي تخضع لـ Zoom's {0}. تتضمن هذه البيانات جميع الملفات المرفقة ولقطات الشاشة ، ومعلومات المستخدم الخاصة بك ، ومعلومات المستخدم لأولئك الذين تبلغهم ، وجميع معلومات الاجتماع ذات الصلة.",
    "wc_security.report_all_privacy_policy_new": "بإرسال هذا التقرير ، فإنك تفوض Zoom للوصول إلى جميع البيانات الموجودة في هذا التقرير ، والتي تخضع لـ Zoom's {0}. تتضمن هذه البيانات لقطات شاشة ، ومعلومات المستخدم الخاصة بك ، ومعلومات المستخدم لأولئك الذين تبلغهم ، وجميع معلومات الاجتماع ذات الصلة.",
    "wc_security.report_cancel_btn": "لا تبلغ",
    "wc_security.report_comments_title": "معلومات إضافية",
    "wc_security.report_email_address": "عنوان بريدك  الإلكتروني",
    "wc_security.report_feedback_new_tips": "سيرسل لك فريق الثقة والأمان بريدًا إلكترونيًا بعد الاجتماع لمعرفة المزيد عن الحادث.",
    "wc_security.report_feedback_new_title": "شكرا لك على تقديم التقرير",
    "wc_security.report_feedback_tips": "سنجري مزيدًا من التحقيق ونتصرف بناءً على نتائجنا. {0} حول طرق تأمين اجتماعك.",
    "wc_security.report_feedback_title": "شكرا على الإبلاغ عن الحادث",
    "wc_security.report_file_format_error": "التنسيق غير مدعوم",
    "wc_security.report_file_size_limit_error1": "يتجاوز ملفك حد 25 ميغا بايت",
    "wc_security.report_file_size_limit_error2": "تتجاوز ملفاتك حد 25 ميغا بايت",
    "wc_security.report_file_upload_error": "فشل التحميل ، يرجى المحاولة مرة أخرى",
    "wc_security.report_hide_screenshot": "إخفاء لقطة الشاشة",
    "wc_security.report_include_desktop_screenshot": "تضمين لقطة شاشة سطح المكتب",
    "wc_security.report_participants_left_label": "اليسار / الإزالة",
    "wc_security.report_privacy_policy": "سياسة الخصوصية",
    "wc_security.report_problem1": "أخرى / سأخبرك لاحقًا",
    "wc_security.report_problem10": "التعدي على حق المؤلف أو العلامة التجارية",
    "wc_security.report_problem11": "التمثيل",
    "wc_security.report_problem2": "فيديو غير لائق",
    "wc_security.report_problem3": "ضيف غير مدعو",
    "wc_security.report_problem4": "سلوك مسيء",
    "wc_security.report_problem5": "التعدي على حق المؤلف أو العلامة التجارية",
    "wc_security.report_problem6": "مسيئة أو غير قانونية أو مسيئة",
    "wc_security.report_problem7": "الانتحار أو إيذاء النفس",
    "wc_security.report_problem8": "معلومات خاصة",
    "wc_security.report_problem9": "رسائل إلكترونية مزعجة",
    "wc_security.report_problem_title": "ما هي المشكلة؟",
    "wc_security.report_remove_users_tip": "ستتم إزالة المستخدمين المبلغ عنهم من اجتماعك",
    "wc_security.report_select_reporter_title": "من الذي تريد الإبلاغ عنه؟",
    "wc_security.report_send": "يرسل",
    "wc_security.report_suspend_success": "تم تعليق أنشطة المشاركين",
    "wc_security.report_title": "تقرير",
    "wc_security.report_view_screenshot": "مشاهدة لقطة الشاشة",
    "wc_security.report_what_happened": "ماذا حدث؟",
    "wc_select": "يختار...",
    "wc_separate_audio_menu_item": "صوت وصورة منفصلان",
    "wc_settings_mask_tips": "مرر لتحديد شكل فيديو مختلف",
    "wc_share": "",
    "wc_share_audio_from_a_chrome_tab_tip": "شارك الصوت من علامة تبويب Chrome",
    "wc_share_audio_note": "ملاحظة: سيتم كتم صوتك أثناء مشاركة الصوت",
    "wc_share_audio_tip": "شارك الصوت من جهاز الكمبيوتر الخاص بك",
    "wc_share_force_stop_sharing_tip": "توقفت مشاركة شاشتك لأن شخصًا ما يشارك من الجلسة الرئيسية.",
    "wc_share_got_it": "فهمتها",
    "wc_share_limit_text": "أنت مقيد من مشاركة الشاشة في هذا الاجتماع",
    "wc_share_muted_while_sharing_audio_tip": "يتم كتم صوتك عند بدء مشاركة الصوت. يمكنك إعادة صوت نفسك عند الانتهاء من المشاركة.",
    "wc_share_to_bo": "شارك في غرف الاستراحة",
    "wc_sharer_controlbar_container_button1_label": "وقفة المشاركة",
    "wc_sharer_controlbar_container_button2_label": "استئناف المشاركة",
    "wc_sharer_controlbar_container_pause_audio_share": "إيقاف مشاركة الصوت",
    "wc_sharer_controlbar_container_play_audio_share": "تشغيل مشاركة الصوت",
    "wc_sharer_controlbar_container_rec_label": "إيقاف التسجيل",
    "wc_sharer_controlbar_container_rec_status_tip3": "أنت تشارك الشاشة",
    "wc_sharer_controlbar_container_rec_status_tip4": "أنت تشارك الشاشة في الغرف الجانبية",
    "wc_sharer_controlbar_container_share_to_bo_label": "شارك في غرف الاستراحة",
    "wc_sharer_device_disabled_by_device_dec": "متصفحك يمنع الوصول إلى شاشة المشاركة الخاصة بك.",
    "wc_sharer_disabled_share_button_label": "نعم",
    "wc_sharer_disabled_share_title": "مشاركة معطل",
    "wc_sharer_entry_button_label2": "مشاركة جديدة",
    "wc_sharer_entry_button_options_label": "خيارات شاشة المشاركة",
    "wc_sharer_in_progress_desc": "معاينة",
    "wc_sharer_setting_menu_advanced_item": "خيارات مشاركة متقدمة ...",
    "wc_sharer_start_share_button1_label": "يلغي",
    "wc_sharer_start_share_button2_label": "يكمل",
    "wc_sharer_start_share_desc": "سيؤدي هذا إلى إيقاف مشاركة الشاشة للآخرين. هل تريد الاستمرار؟",
    "wc_sharer_start_share_title": "ابدأ بالمشاركة",
    "wc_sharing_exit_full_screen": "الخروج من الشاشة الكاملة",
    "wc_sharing_full": "ممتلىء",
    "wc_sharing_full_screen": "تكبير الشاشة",
    "wc_sharing_limit_text": "لأنك ممنوع من مشاركة الشاشة في حالة وجود مستخدمين خارجيين",
    "wc_sharing_limit_title": "توقفت مشاركة شاشتك",
    "wc_sharing_menu_option1": "حصة في الجلسة الرئيسية فقط",
    "wc_sharing_menu_option2": "شارك في الجلسة الرئيسية وغرف الاجتماعات الفرعية",
    "wc_sharing_no_full": "لا ممتلئ",
    "wc_sharing_notify_text": "يمكن للمشاركين الآن رؤية شاشتك",
    "wc_sharing_setting_title": "خيارات مشاركة متقدمة",
    "wc_sharing_to_bo_confirm_dialog_content1": "ستتم مشاركة شاشتك في الجلسة الرئيسية وفي جميع الغرف الجانبية",
    "wc_sharing_to_bo_confirm_dialog_content2": "لن تتم مشاركة الفيديو والصوت الخاصين بك مع Breakout Rooms",
    "wc_sharing_to_bo_confirm_dialog_content3": "سيتم إيقاف الشاشات التي يشاركها الآخرون في الغرف",
    "wc_sharing_to_bo_confirm_dialog_title": "مشاركة الشاشة في جميع الغرف الجانبية",
    "wc_sign_in_fail": "فشل تسجيل الدخول",
    "wc_sip": "رشفة",
    "wc_start_focus_mode": "بدء وضع التركيز؟",
    "wc_stop_focus_mode": "وقف وضع التركيز",
    "wc_stop_recording": "إيقاف التسجيل",
    "wc_stop_recording_content": "إذا كانت الإجابة بنعم ، فستتلقى إشعارًا بالبريد الإلكتروني عندما يكون التسجيل السحابي جاهزًا.",
    "wc_stop_share_to_bo": "توقف عن المشاركة في الغرف الفرعية",
    "wc_timeout": "نفذ الوقت",
    "wc_trying_to_reconnect": "تحاول إعادة الاتصال",
    "wc_trying_to_register": "محاولة التسجيل",
    "wc_trying_to_sign": "أحاول تسجيل الدخول",
    "wc_unable_pc_audio": "تعذر استخدام صوت الكمبيوتر.",
    "wc_unknown_error": "خطأ غير معروف.",
    "wc_unknown_error_action": "حدث خطأ غير معروف ، يرجى محاولة تحديث هذه الصفحة للانضمام إلى الاجتماع مرة أخرى.",
    "wc_unknown_error_btn": "ينعش",
    "wc_unlock_meeting": "افتح الاجتماع",
    "wc_unlock_meeting_content": "يمكن للحاضرين الجدد الانضمام إلى هذا الاجتماع بمجرد إلغاء قفله.",
    "wc_unmute_by_host_btn2": "قم بالتبديل إلى صوت الكمبيوتر لإلغاء كتم الصوت",
    "wc_unmute_by_host_content": "يرغب المضيف في إعادة صوت الميكروفون",
    "wc_unmute_dialog_tip1": "سيؤدي النقر فوق إلغاء كتم الصوت إلى توصيل صوت الكمبيوتر وإلغاء كتم الصوت.",
    "wc_unmute_dialog_tip2": "انضم بالفعل عن طريق الهاتف؟ أدخل # {0} # على هاتفك ، ثم انقر على \"إلغاء كتم الصوت\".",
    "wc_update_browser": "قم بتحديث المتصفح إلى أحدث إصدار من Chrome لتجربة مكبر الصوت وعرض المعرض",
    "wc_update_browser_to_share": "قم بتحديث متصفحك إلى أحدث إصدار من Chrome لاستخدام Share Screen",
    "wc_update_browser_to_share_multiview": "قم بتحديث متصفحك إلى أحدث إصدار من Chrome لاستخدام مشاركة الشاشة ومكبر الصوت / عرض المعرض",
    "wc_upgrade_browser": "لا يدعم متصفحك استخدام جهاز الصوت في الكمبيوتر ، يرجى ترقية المتصفح إلى أحدث إصدار.",
    "wc_url_copied_to_clipboard": "تم نسخ URL إلى الحافظة",
    "wc_video.add_spotlight": "أضف Spotlight",
    "wc_video.camera_is_taken": "احتلت تطبيقات أخرى الكاميرا الخاصة بك ، يرجى تحرير الامتياز والمحاولة مرة أخرى.",
    "wc_video.cancel_spotlight_video": "قم بإلغاء Spotlight Video",
    "wc_video.cannot_detect_camera": "لا يمكن الكشف عن الكاميرا الخاصة بك ، يرجى التحقق من الجهاز والاتصال والمحاولة مرة أخرى.",
    "wc_video.check_permission": "لم يتم تشغيل الكاميرا بشكل صحيح ، يرجى التحقق من إعدادات أذونات وسائط المتصفح.",
    "wc_video.meeting_alert": "تنبيه الاجتماع",
    "wc_video.ok": "نعم",
    "wc_video.spotlight_video": "فيديو مميز",
    "wc_video_setting": "إعداد الفيديو...",
    "wc_waiting_room_admit_all": "قبول الجميع",
    "wc_waiting_room_mention_in_bo": "سيتم قبول المشاركين في الجلسة الرئيسية",
    "wc_waiting_room_title1": "الشخص ينتظر",
    "wc_waiting_room_title2": "الناس ينتظرون",
    "wc_waiting_room_title3": "الشخص قيد الانتظار",
    "wc_waiting_room_title4": "الناس في الانتظار",
    "wc_webinar_attendee": "حاضر",
    "wc_webinar_depromote": "{0} سينضم مرة أخرى إلى الندوة على الويب كأحد الحاضرين.",
    "wc_webinar_depromote_error": "فشل تغيير الدور إلى الحضور",
    "wc_webinar_not_start": "الندوة عبر الإنترنت لم تبدأ",
    "wc_webinar_panelist": "المتحدث",
    "wc_webinar_practice_broadcast": "إذاعة",
    "wc_webinar_promote": "{0} سينضم مرة أخرى إلى الندوة على الويب كأحد أعضاء اللجنة.",
    "wc_webinar_promote_error": "الترقية إلى عضو اللجنة فشلت",
    "wc_webinar_seecounts": "السماح للحاضرين بعرض أعداد المشاركين",
    "wc_webinar_takeoffhold": "خلع عقد",
    "wc_webinar_timeout": "انتهت مهلة اتصالك ولا يمكنك الانضمام إلى الندوة عبر الإنترنت. تحقق من اتصال الشبكة وحاول مرة أخرى.",
    "wc_webinar_timeout_title": "انتهت مهلة الانضمام إلى الندوة التعليمية على الويب.",
    "wc_yahoo_email": "بريد ياهو",
    "wc_you": "(أنت)",
    "webinar": "ندوة عبر الإنترنت",
    "webinar_disconnected": "تم قطع اتصال الويبينار",
    "webinar_registration_unsupport": "التسجيل في ندوة الويب غير مدعوم",
    "webinar_registration_unsupport_contant": "يرجى التحديث إلى أحدث إصدار من WebSDK لدعم التسجيل في الندوة عبر الإنترنت. انتقل إلى التحقق من بريدك الإلكتروني ، واستخدم Zoom Client / Webclient Join.",
    "websdk_update": "تحديث",
    "websdk_update_title": "مطلوب التحديث",
    "wrong_pass": "رمز المرور خاطئ"
}
